In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.special import erf
from scipy.stats import norm
%matplotlib inline
#%matplotlib tk

In [2]:
SPXtarr = np.array([0.119047619047619, 0.238095238095238, 0.357142857142857,
             0.476190476190476, 0.595238095238095, 0.714285714285714,
             1.07142857142857,  1.42857142857143])
SPXtarr * 252

array([ 30.,  60.,  90., 120., 150., 180., 270., 360.])

In [3]:
SPXmaturities = np.array([0.08219178, 0.16438356, 0.24657534, 0.32876712, 0.4109589 ,0.49315068, 0.73972603, 0.98630137])
VIXmaturities = np.array([7, 14, 21, 30, 60, 90])/365
deltas = np.array([0.9, 0.75, 0.5, 0.25, 0.1])

In [4]:
VIXmaturities

array([0.01917808, 0.03835616, 0.05753425, 0.08219178, 0.16438356,
       0.24657534])

In [14]:
k = 3.0
vbar = 0.1 * 100
v0 = 0.08
rho = -0.8
sigma = 0.25
r = 0.02

In [6]:
def strike(delta, tau):
    d1 = norm.ppf(delta)
    k = v0/np.exp(d1 * sigma * np.sqrt(tau) - (r + sigma**2 * 0.5)*tau)
    return k

In [15]:
for tau in VIXmaturities:
    for delta in deltas:

        k = strike(delta, tau)
        print(f'{k},')

0.07660333466800909,
0.07823036262505452,
0.08007866879151475,
0.08197064388101638,
0.08371167160297435,
0.07528231789011931,
0.07755350918528185,
0.08015741494276396,
0.08284874840358378,
0.0853482112450969,
0.07430112345712658,
0.077055734551228,
0.08023623852982013,
0.08354801898792094,
0.08664544590808211,
0.0732872469748735,
0.07654634796281677,
0.08033769704753065,
0.08431683207193616,
0.08806642128491488,
0.07084911309063555,
0.07534553012964565,
0.08067681958626018,
0.08638533974549638,
0.0918677586016848,
0.06910110193769552,
0.07450988995253548,
0.08101737363349071,
0.08809320258894406,
0.0949885695945464,


In [16]:
sigma = 0.08
v0 = 1
for delta in deltas:
    for tau in SPXmaturities:
    

        k = strike(delta, tau)
        print(f'{k},')

0.9728883965569388,
0.9629498634949916,
0.9558166302191722,
0.9501284349297767,
0.9453595503163794,
0.9412409156648102,
0.9314464152996802,
0.9240978710004466,
0.9865287931820181,
0.982098527453292,
0.9791468839248835,
0.9769577867538504,
0.9752544510919837,
0.9738952084195568,
0.971176355610958,
0.9697605143698358,
1.0019086684892442,
1.0038209799938902,
1.0057369414672468,
1.007656559875894,
1.0095798421997093,
1.0115067954318921,
1.017309750947023,
1.0231459974422654,
1.0175283143597833,
1.0260238985276533,
1.033049087974722,
1.0393199751595301,
1.045113361579374,
1.0505709324366257,
1.0656346021941978,
1.0794703605377993,
1.031794585634305,
1.0464268162608605,
1.0582644865678366,
1.0686678825015554,
1.0781627555726092,
1.0870181907490015,
1.111088209018361,
1.1328104575642102,


In [17]:
allT = np.array([0, 7, 14, 21, 30, 37, 44, 51, 60, 90, 120, 150, 180, 270, 360])/365

In [3]:
np.random.rand(14) * 0.001

array([1.46371706e-04, 4.31183274e-04, 7.89958945e-04, 2.91974407e-04,
       8.57045896e-05, 5.48371267e-04, 4.84620007e-04, 3.51856480e-04,
       7.00281831e-04, 7.14263885e-04, 7.51713276e-04, 6.58928904e-04,
       4.95814626e-04, 6.67154021e-04])

In [18]:
allT.cumsum()

array([0.        , 0.01917808, 0.05753425, 0.11506849, 0.19726027,
       0.29863014, 0.41917808, 0.55890411, 0.72328767, 0.96986301,
       1.29863014, 1.70958904, 2.20273973, 2.94246575, 3.92876712])

In [19]:
allT

array([0.        , 0.01917808, 0.03835616, 0.05753425, 0.08219178,
       0.10136986, 0.12054795, 0.13972603, 0.16438356, 0.24657534,
       0.32876712, 0.4109589 , 0.49315068, 0.73972603, 0.98630137])

In [20]:
disStar = np.array([0.91840917, 0.50851988, 0.25907174, 0.85560232, 0.53713517,
                     0.02042697, 0.54469571, 0.89533401, 0.96375783, 0.83626845,
                     0.93122131, 1.36544665, 0.90517004, 0.98858194])


In [21]:
disStar.cumsum()

array([ 0.91840917,  1.42692905,  1.68600079,  2.54160311,  3.07873828,
        3.09916525,  3.64386096,  4.53919497,  5.5029528 ,  6.33922125,
        7.27044256,  8.63588921,  9.54105925, 10.52964119])

In [26]:
np.array([0.50851988, 0.25907174, 0.85560232, 0.53713517]).cumsum()

array([0.50851988, 0.76759162, 1.62319394, 2.16032911])