In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.special import erf
from scipy.stats import norm
%matplotlib inline
#%matplotlib tk

In [11]:
SPXtarr = np.array([0.119047619047619, 0.238095238095238, 0.357142857142857,
             0.476190476190476, 0.595238095238095, 0.714285714285714,
             1.07142857142857,  1.42857142857143])
SPXtarr * 252

array([ 30.,  60.,  90., 120., 150., 180., 270., 360.])

In [12]:
SPXmaturities = np.array([0.08219178, 0.16438356, 0.24657534, 0.32876712, 0.4109589 ,0.49315068, 0.73972603, 0.98630137])
VIXmaturities = np.array([7, 14, 21, 30, 60, 90])/365
deltas = np.array([0.9, 0.75, 0.5, 0.25, 0.1])

In [13]:
VIXmaturities

array([0.01917808, 0.03835616, 0.05753425, 0.08219178, 0.16438356,
       0.24657534])

In [14]:
k = 3.0
vbar = 0.1
v0 = 0.08
rho = -0.8
sigma = 0.25
r = 0.02

In [15]:
def strike(delta, tau):
    d1 = norm.ppf(delta)
    k = v0/np.exp(d1 * sigma * np.sqrt(tau) - (r + sigma**2 * 0.5)*tau)
    return k

In [16]:
for tau in VIXmaturities:
    for delta in deltas:

        k = strike(delta, tau)
        print(f'{k}')

0.07660333466800909
0.07823036262505452
0.08007866879151475
0.08197064388101638
0.08371167160297435
0.07528231789011931
0.07755350918528185
0.08015741494276396
0.08284874840358378
0.0853482112450969
0.07430112345712658
0.077055734551228
0.08023623852982013
0.08354801898792094
0.08664544590808211
0.0732872469748735
0.07654634796281677
0.08033769704753065
0.08431683207193616
0.08806642128491488
0.07084911309063555
0.07534553012964565
0.08067681958626018
0.08638533974549638
0.0918677586016848
0.06910110193769552
0.07450988995253548
0.08101737363349071
0.08809320258894406
0.0949885695945464


In [8]:
sigma = 0.08
v0 = 1
for tau in SPXtarr:
    for delta in deltas:

        k = strike(delta, tau)
        print(f'{k}')

0.967913767190866
0.9842692600422481
1.0027657223346433
1.0216097715437724
1.0388726020579824
0.956472882627603
0.9794093683789121
1.0055390938893192
1.032365936026637
1.0571223583067564
0.9483950258993076
0.9763237235881492
1.0083201358196459
1.0413651453257486
1.0720316624765749
0.9420463999378
0.9741521727452975
1.011108869339753
1.0494676029684487
1.0852343851905968
0.9367961690795298
0.9725625494293157
1.013905315722442
1.0570055261262539
1.0973614359037283
0.9323217746699008
0.971384989139781
1.0167094962993493
1.0641488301982898
1.1087354472990496
0.9219489655170625
0.9694795336326241
1.0251686573976835
1.0840566919165364
1.1399446340515673
0.9144825338166894
0.9691356390107899
1.0336981998652763
1.1025618348896735
1.1684553054776035


In [17]:
allT = np.array([0, 7, 14, 21, 30, 37, 44, 51, 60, 90, 120, 150, 180, 270, 360])/365

In [3]:
np.random.rand(14) * 0.001

array([1.46371706e-04, 4.31183274e-04, 7.89958945e-04, 2.91974407e-04,
       8.57045896e-05, 5.48371267e-04, 4.84620007e-04, 3.51856480e-04,
       7.00281831e-04, 7.14263885e-04, 7.51713276e-04, 6.58928904e-04,
       4.95814626e-04, 6.67154021e-04])

In [18]:
allT.cumsum()

array([0.        , 0.01917808, 0.05753425, 0.11506849, 0.19726027,
       0.29863014, 0.41917808, 0.55890411, 0.72328767, 0.96986301,
       1.29863014, 1.70958904, 2.20273973, 2.94246575, 3.92876712])

In [19]:
allT

array([0.        , 0.01917808, 0.03835616, 0.05753425, 0.08219178,
       0.10136986, 0.12054795, 0.13972603, 0.16438356, 0.24657534,
       0.32876712, 0.4109589 , 0.49315068, 0.73972603, 0.98630137])

In [20]:
disStar = np.array([0.91840917, 0.50851988, 0.25907174, 0.85560232, 0.53713517,
                     0.02042697, 0.54469571, 0.89533401, 0.96375783, 0.83626845,
                     0.93122131, 1.36544665, 0.90517004, 0.98858194])


In [21]:
disStar.cumsum()

array([ 0.91840917,  1.42692905,  1.68600079,  2.54160311,  3.07873828,
        3.09916525,  3.64386096,  4.53919497,  5.5029528 ,  6.33922125,
        7.27044256,  8.63588921,  9.54105925, 10.52964119])

In [26]:
np.array([0.50851988, 0.25907174, 0.85560232, 0.53713517]).cumsum()

array([0.50851988, 0.76759162, 1.62319394, 2.16032911])