In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.special import erf
from scipy.stats import norm
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
#%matplotlib tk

In [538]:
mu002 = pd.read_csv("/home/lin/git/summerProject/Heston_10000_front1_K1_max100_muFactor0.02")
mu01 = pd.read_csv("/home/lin/git/summerProject/Heston_10000_front1_K1_max100_muFactor0.1")
mu05 = pd.read_csv("/home/lin/git/summerProject/Heston_10000_front1_K1_max100_muFactor0.5")
mu2 = pd.read_csv("/home/lin/git/summerProject/Heston_10000_front1_K1_max100_muFactor2")
mu10 = pd.read_csv("/home/lin/git/summerProject/Heston_10000_front1_K1_max100_muFactor10")
mu50 = pd.read_csv("/home/lin/git/summerProject/Heston_10000_front1_K1_max100_muFactor50")
mu100 = pd.read_csv("/home/lin/git/summerProject/Heston_10000_front1_K1_max100_muFactor100")

In [539]:
compare = pd.DataFrame(index=['002', '01', '05', '2', '10', '50', '100'], columns = mu002.columns)
compare.loc['002', :] = mu002.mean().values
compare.loc['01', :] = mu01.mean().values
compare.loc['05', :] = mu05.mean().values
compare.loc['2', :] = mu2.mean().values
compare.loc['10', :] = mu10.mean().values
compare.loc['50', :] = mu50.mean().values
compare.loc['100', :] = mu100.mean().values

compare

Ik     Ivbar       Iv0      Irho    Isigma       Ok       Rk  \
002  2.98213  0.485305  0.507122 -0.494167    0.5044   2.8024  2.79146   
01   2.91564  0.483326  0.507004 -0.487946  0.493368  2.73647  2.73693   
05   2.92499   0.47323  0.501108 -0.482363  0.496859  2.74668  2.75183   
2    2.91837  0.477597  0.492619 -0.485969  0.528472  2.70657  2.72535   
10   2.81641  0.484258  0.480721 -0.486076  0.516278  2.71991  2.76695   
50   2.77142  0.494511   0.50195 -0.486056  0.519509  2.72433   2.7676   
100  2.71616  0.492674  0.509474 -0.492822  0.533495  2.68766  2.73186   

        Ovbar     Rvbar       Ov0   ...       time iteration       pv  \
002  0.499294   0.50179  0.502242   ...    9.71495      47.2   58.453   
01   0.494461  0.498955  0.488388   ...    9.23053    46.949    57.11   
05   0.500425  0.504527  0.484095   ...    8.76697     48.01   57.467   
2    0.508663  0.510509  0.503261   ...    8.90216    48.893   57.659   
10   0.504286  0.507207  0.519016   ...    10.1036    52.898   61.615   
50   0.493389  0.494508  0.501179   ...    8.36727     57.07   65.487   
100  0.510731  0.514872  0.511768   ...    6.07172   56.1373  64.4182   

         jac  lin_sys           e0           e*           Je           Dp  \
002   47.212   57.707  7.56907e+09   0.00988144      519.823      3.19738   
01    46.955   56.323  7.53244e+09    0.0228277          inf      0.81035   
05    48.016   56.585  2.34674e+08  0.000827517      67050.5    0.0834436   
2     48.897   56.731  1.79528e+08  0.000434436      51.7988  2.70355e-05   
10    52.899   60.693  3.89786e+07  4.11168e-05  8.12359e-05  0.000140402   
50    57.075    64.54   7.6145e+08  6.20842e-05    0.0101773  3.05342e-05   
100  56.1426  63.4885  9.88763e+07  0.000539628      7.38725   3.4635e-05   

      count  
002  18.938  
01   15.803  
05   13.312  
2    13.715  
10   16.307  
50   12.669  
100  14.282  

[7 rows x 26 columns]

In [536]:
compare['pv'] / compare['iteration']

002    1.23841
01     1.21643
05     1.19698
2      1.17929
10     1.16479
50     1.14749
dtype: object

In [500]:
result.columns

Index(['Ik', 'Ivbar', 'Iv0', 'Irho', 'Isigma', 'Ok', 'Rk', 'Ovbar', 'Rvbar',
       'Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma', 'stopped_by', 'time',
       'iteration', 'pv', 'jac', 'lin_sys', 'e0', 'e*', 'Je', 'Dp', 'count'],
      dtype='object')

In [501]:
result['stopped_by'].unique() #3, itmax, 1 small gradient, 5 increase mu

array([6, 2, 1, 3])

In [540]:
solved002 = mu002[mu002['stopped_by'] == 6]
solved002.count().unique()

array([832])

In [541]:
solved01 = mu01[mu01['stopped_by'] == 6]
solved01.count().unique()

array([866])

In [542]:
solved05 = mu05[mu05['stopped_by'] == 6]
solved05.count().unique()

array([892])

In [543]:
solved2 = mu2[mu2['stopped_by'] == 6]
solved2.count().unique()

array([879])

In [545]:
solved10 = mu10[mu10['stopped_by'] == 6]
solved10.count().unique()

array([869])

In [546]:
solved50 = mu50[mu50['stopped_by'] == 6]
solved50.count().unique()

array([880])

In [547]:
solved100 = mu100[mu100['stopped_by'] == 6]
solved100.count().unique()

array([827])

In [503]:
solved.count().unique()/result.count().unique()

array([0.88191882])

In [504]:
DP = result[result['stopped_by'] == 2]
DP.count().unique()

array([45])

In [505]:
invalid_value = result[result['stopped_by'] == 7]
invalid_value.count().unique()

array([0])

In [506]:
DP

Ik     Ivbar       Iv0      Irho    Isigma        Ok        Rk  \
14   1.105046  0.181427  0.907565 -0.406974  0.880674  2.613155  2.706224   
26   2.172924  0.911116  0.161429 -0.292908  0.549436  2.233592  3.035306   
83   4.115670  0.790669  0.807992 -0.424512  0.774898  4.117057  1.585056   
106  1.692494  0.303552  0.903272 -0.122480  0.539290  1.731928  4.479792   
107  1.191421  0.054267  0.476511 -0.682252  0.485205  1.151291  2.471362   
114  4.704287  0.221052  0.240227 -0.588729  0.450743  4.683783  2.139504   
128  3.064062  0.398148  0.702633 -0.287573  0.239112  3.039467  2.694948   
133  3.977017  0.528487  0.939800 -0.414652  0.822402  2.326198  1.776415   
200  3.971825  0.397035  0.401840 -0.877292  0.208122  3.985787  4.835225   
208  1.357275  0.354216  0.798441 -0.143057  0.183843  2.000138  3.686562   
210  1.670119  0.558020  0.839676 -0.189273  0.554631  4.322484  4.893333   
213  1.870732  0.706123  0.225283 -0.179968  0.367166  1.908508  4.550699   
227  2.890168  0.118086  0.632113 -0.603599  0.877840  3.477034  3.495666   
259  4.956344  0.056738  0.845063 -0.572132  0.425964  4.841940  0.974000   
307  3.782967  0.051571  0.109025 -0.365842  0.516925  3.788954  4.389374   
310  0.888955  0.227076  0.491192 -0.415058  0.524665  0.913974  3.967546   
320  4.796322  0.507228  0.428729 -0.396909  0.209758  2.581074  2.520896   
341  4.897923  0.727804  0.269475 -0.797610  0.827801  4.718586  4.690251   
348  4.691529  0.783885  0.499634 -0.654444  0.308543  4.670536  1.574281   
350  0.711463  0.940722  0.833995 -0.441200  0.435116  0.682542  1.385557   
371  4.687745  0.344879  0.301197 -0.869629  0.279809  4.664384  4.475103   
392  1.748955  0.456849  0.766435 -0.280780  0.636039  1.689576  2.470203   
481  4.373817  0.532999  0.320862 -0.329041  0.502249  4.343611  3.241874   
497  3.130298  0.690099  0.417304 -0.113183  0.095722  3.183722  3.043555   
505  4.884330  0.157880  0.290101 -0.860601  0.268482  4.849204  1.481883   
520  2.490971  0.404678  0.534587 -0.115042  0.564744  2.502084  4.757137   
543  2.207008  0.573864  0.242083 -0.427826  0.625999  3.219565  3.520791   
561  4.035777  0.905248  0.754501 -0.108620  0.359878  0.645300  0.611140   
574  4.016059  0.828167  0.344324 -0.825763  0.464134  4.045137  2.084584   
587  1.342974  0.931988  0.108720 -0.612482  0.116998  2.435197  4.740407   
597  3.297330  0.682682  0.622540 -0.722154  0.536412  3.304963  3.033092   
605  0.929956  0.629449  0.844695 -0.502163  0.768791  0.930640  1.420542   
620  3.255073  0.215647  0.484356 -0.599785  0.191035  3.224541  2.888075   
632  4.342082  0.125734  0.457826 -0.256813  0.182664  1.951561  1.462237   
646  1.947363  0.588653  0.299991 -0.795688  0.802587  1.935217  1.473093   
690  0.602467  0.593343  0.271194 -0.360713  0.725472  2.803525  3.519812   
694  1.771401  0.305911  0.936492 -0.820116  0.727670  2.415179  4.433042   
708  2.466999  0.915349  0.821022 -0.635678  0.880410  4.045216  4.132112   
755  1.030396  0.825973  0.738427 -0.537931  0.225964  3.681686  4.373617   
758  1.503735  0.238114  0.557499 -0.697727  0.702349  1.653217  2.960184   
767  2.294205  0.760343  0.813706 -0.666450  0.143514  1.773926  1.699013   
780  1.270281  0.781422  0.282073 -0.445520  0.675790  1.307044  4.418474   
799  4.522868  0.346655  0.919867 -0.437667  0.741683  4.544864  4.994921   
809  0.822962  0.169171  0.075745 -0.275573  0.674924  0.908466  3.241294   
812  1.079943  0.739448  0.637089 -0.422039  0.571762  4.847751  4.931067   

        Ovbar     Rvbar       Ov0  ...         time  iteration   pv  jac  \
14   0.292016  0.298147  0.861284  ...    56.928898         74  113   74   
26   0.152597  0.215521  0.749902  ...    39.528481          4   12    4   
83   0.352734  0.366883  0.343939  ...    63.725652          8   18    8   
106  0.496027  0.546359  0.684876  ...    57.933718          8   19    8   
107  0.487933  0.505795  0.536196  ...    44.782680          9   20    9   
114  0.30025

In [507]:
invalid_value

Empty DataFrame
Columns: [Ik, Ivbar, Iv0, Irho, Isigma, Ok, Rk, Ovbar, Rvbar, Ov0, Rv0, Orho, Rrho, Osigma, Rsigma, stopped_by, time, iteration, pv, jac, lin_sys, e0, e*, Je, Dp, count]
Index: []

[0 rows x 26 columns]

In [508]:
itmax = result[result['stopped_by'] == 3]
itmax.count().unique()

array([48])

In [509]:
smalJac = result[result['stopped_by'] == 1]
smalJac.count().unique()

array([3])

In [510]:
solved['time'].describe()

count    717.000000
mean       5.275794
std        9.328446
min        0.305718
25%        0.921238
50%        1.875799
75%        4.893873
max       71.348150
Name: time, dtype: float64

In [511]:
solved['e*'].describe()

count    7.170000e+02
mean     6.004764e-11
std      3.124486e-11
min      3.176682e-14
25%      3.570409e-11
50%      6.735698e-11
75%      8.802231e-11
max      9.985158e-11
Name: e*, dtype: float64

In [512]:
solved_first_time = solved[solved['count'] == 1]
solved_first_time.count().unique()

array([295])

In [513]:
solved_first_time['time'].describe()

count    295.000000
mean       1.172421
std        1.099731
min        0.305718
25%        0.606177
50%        0.848589
75%        1.326761
max        8.095660
Name: time, dtype: float64

In [514]:
solved_first_time['iteration'].describe()

count    295.000000
mean      40.355932
std       38.588692
min       11.000000
25%       21.000000
50%       29.000000
75%       44.500000
max      283.000000
Name: iteration, dtype: float64

In [515]:
solved['iteration'].describe()

count    717.000000
mean      42.299861
std       40.515197
min       11.000000
25%       21.000000
50%       30.000000
75%       47.000000
max      296.000000
Name: iteration, dtype: float64

In [279]:
solved.head()

Ik     Ivbar       Iv0      Irho    Isigma        Ok        Rk  \
0  2.837374  0.081115  0.526730 -0.106159  0.110158  1.092136  1.091920   
1  3.929891  0.092718  0.345411 -0.705128  0.378805  3.590685  3.590477   
2  2.649793  0.297416  0.199856 -0.818125  0.104508  4.921271  4.921476   
3  2.228640  0.872436  0.468001 -0.140067  0.743184  2.769455  2.770353   
4  1.878448  0.511946  0.811383 -0.773209  0.423855  1.065402  1.064144   

      Ovbar     Rvbar       Ov0  ...        time  iteration  pv  jac  lin_sys  \
0  0.462748  0.462785  0.247065  ...    0.372658         38  59    4       38   
1  0.887387  0.887393  0.524235  ...    0.264193         24  40    3       24   
2  0.728025  0.728020  0.115419  ...    0.258905         23  39    3       23   
3  0.337115  0.337130  0.494573  ...    0.249213         23  39    3       23   
4  0.669523  0.669610  0.616609  ...    0.162645         15  26    2       15   

          e0            e*        Je        Dp  count  
0  14.479054  2.210737e-11  0.000112  0.000003      1  
1   0.368665  9.805093e-13  0.000011  0.000007      1  
2   0.142270  1.327448e-11  0.000127  0.000003      1  
3   0.144686  3.443611e-11  0.000004  0.000022      1  
4   0.041754  9.334175e-11  0.000033  0.000117      1  

[5 rows x 26 columns]

In [280]:
#'Ik', 'Ivbar', 'Iv0', 'Irho', 'Isigma', 'Ok', 'Rk', 'Ovbar', 'Rvbar',
#'Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma', 'stopped_by', 'time',
#'iteration', 'pv', 'jac', 'lin_sys', 'e0', 'e*', 'Je', 'Dp', 'count'
   

In [281]:
disIk = np.abs(solved['Ik'] - solved['Rk']).mean()
disIk

1.4671820770406407

In [282]:
disIvbar = np.abs(solved['Ivbar'] - solved['Rvbar']).mean()
disIvbar

0.3012198319293554

In [283]:
disIv0 = np.abs(solved['Iv0'] - solved['Rv0']).mean()
disIv0

0.296581946565592

In [284]:
disIsigma = np.abs(solved['Isigma'] - solved['Rsigma']).mean()
disIsigma

0.299108464718648

In [285]:
disIrho = np.abs(solved['Irho'] - solved['Rrho']).mean()
disIrho

0.26666581933554134

In [286]:
disOk = np.abs(solved['Ok'] - solved['Rk']).mean()
disOk

0.0017588290696306922

In [287]:
disOvbar = np.abs(solved['Ovbar'] - solved['Rvbar']).mean()
disOvbar

3.91338674305753e-05

In [288]:
disOsigma = np.abs(solved['Osigma'] - solved['Rsigma']).mean()
disOsigma

0.03462990461048819

In [289]:
disOrho = np.abs(solved['Orho'] - solved['Rrho']).mean()
disOrho

0.03768302318421371

In [290]:
disOv0 = np.abs(solved['Ov0'] - solved['Rv0']).mean()
disOv0

6.379059950038386e-06

In [31]:
solved.describe()

Ik        Ivbar          Iv0         Irho       Isigma  \
count  8949.000000  8949.000000  8949.000000  8949.000000  8949.000000   
mean      2.993421     0.488570     0.500875    -0.489544     0.504134   
std       1.248795     0.258190     0.255068     0.229477     0.258389   
min       0.502552     0.050041     0.050007    -0.899978     0.050007   
25%       1.977381     0.263228     0.283898    -0.687947     0.282309   
50%       3.097229     0.484192     0.498901    -0.484705     0.510624   
75%       4.058899     0.708973     0.721273    -0.291594     0.726292   
max       4.999791     0.949943     0.949656    -0.100029     0.949977   

                Ok           Rk        Ovbar        Rvbar          Ov0  \
count  8949.000000  8949.000000  8949.000000  8949.000000  8949.000000   
mean      2.779487     2.779501     0.501063     0.501071     0.484424   
std       1.281260     1.281951     0.266929     0.266960     0.263053   
min       0.502960     0.502710     0.050009     0.050009     0.050263   
25%       1.660451     1.660249     0.259709     0.259667     0.248187   
50%       2.782766     2.783323     0.512606     0.512725     0.479528   
75%       3.877782     3.880238     0.736886     0.736904     0.714033   
max       5.000173     4.999420     0.949636     0.949810     0.949998   

          ...              time    iteration           pv          jac  \
count     ...       8949.000000  8949.000000  8949.000000  8949.000000   
mean      ...          1.127488    33.476590    40.382948    33.476590   
std       ...          1.556067    30.174241    32.848398    30.174241   
min       ...          0.087668     6.000000     7.000000     6.000000   
25%       ...          0.316021    18.000000    21.000000    18.000000   
50%       ...          0.548002    25.000000    31.000000    25.000000   
75%       ...          1.188484    37.000000    47.000000    37.000000   
max       ...         20.444751   299.000000   343.000000   299.000000   

           lin_sys            e0            e*            Je            Dp  \
count  8949.000000  8.949000e+03  8.949000e+03  8.949000e+03  8.949000e+03   
mean     39.382948  7.757969e+08  5.884779e-11  5.623609e-05  4.068706e-05   
std      32.848398  2.804782e+10  3.136440e-11  1.511267e-03  3.244039e-04   
min       6.000000  6.877603e-05  1.259546e-14  4.709341e-10  8.058025e-12   
25%      20.000000  4.863627e-02  3.230283e-11  1.082327e-06  2.241636e-07   
50%      30.000000  1.393358e-01  6.592811e-11  1.856651e-06  1.045751e-06   
75%      46.000000  7.197198e-01  8.713487e-11  4.162652e-06  8.829198e-06   
max     342.000000  1.902894e+12  9.999167e-11  1.333074e-01  1.433280e-02   

             count  
count  8949.000000  
mean      3.153201  
std       4.575754  
min       1.000000  
25%       1.000000  
50%       1.000000  
75%       3.000000  
max      30.000000  

[8 rows x 26 columns]

In [32]:
solved[solved['iteration']==30]

Ik     Ivbar       Iv0      Irho    Isigma        Ok        Rk  \
182   2.443999  0.827914  0.192582 -0.206408  0.230323  2.083332  2.084339   
273   2.194674  0.210438  0.789052 -0.191293  0.185954  1.488799  1.490523   
467   4.442036  0.398225  0.735406 -0.112383  0.064883  1.436033  1.435766   
547   4.799829  0.865675  0.615263 -0.376252  0.600131  1.758230  1.753561   
567   2.003108  0.766503  0.278598 -0.606551  0.217312  0.819289  0.819279   
573   1.476241  0.488112  0.391280 -0.523332  0.517428  0.751721  0.751766   
586   3.514128  0.642997  0.644815 -0.781660  0.215824  3.735146  3.735043   
594   1.771362  0.071418  0.769358 -0.231586  0.477418  4.540222  4.544727   
619   2.537582  0.166297  0.892470 -0.555293  0.107960  3.872981  3.876983   
748   4.601053  0.604873  0.681964 -0.584889  0.512424  4.206418  4.201392   
751   4.275124  0.831533  0.595203 -0.353084  0.151017  0.658300  0.658088   
755   1.978688  0.708750  0.728498 -0.890129  0.350675  4.040346  4.040690   
783   3.821233  0.176696  0.082164 -0.565162  0.090983  4.793873  4.796322   
826   2.807317  0.463689  0.490856 -0.714130  0.789095  4.918860  4.918821   
895   3.498299  0.698802  0.795737 -0.578385  0.233022  1.099622  1.099265   
920   3.387480  0.691319  0.652807 -0.262106  0.947794  3.172786  3.164330   
939   0.918486  0.421617  0.775471 -0.274897  0.677272  4.283315  4.283080   
961   0.888840  0.713686  0.609123 -0.436901  0.069545  3.209030  3.209463   
1009  3.908028  0.712636  0.947426 -0.655837  0.094874  4.404953  4.405946   
1058  0.557997  0.618903  0.330763 -0.675497  0.322424  0.516333  0.516275   
1079  0.626367  0.127086  0.288560 -0.425571  0.253173  2.372060  2.372903   
1117  4.985554  0.702215  0.758815 -0.173408  0.214349  4.879144  4.879350   
1152  4.947379  0.239097  0.856109 -0.428874  0.140694  3.672407  3.667426   
1229  2.322015  0.527172  0.522046 -0.316169  0.051727  3.459483  3.463060   
1260  2.037844  0.184023  0.294202 -0.830000  0.667040  1.971261  1.971033   
1290  4.158269  0.161163  0.948322 -0.138101  0.588258  4.817928  4.823287   
1305  3.153070  0.069137  0.794391 -0.761306  0.446547  1.104765  1.103375   
1316  4.190924  0.505900  0.657472 -0.328910  0.111174  2.964241  2.962873   
1330  1.288084  0.473751  0.154954 -0.148575  0.862397  2.737771  2.739728   
1475  3.453492  0.064682  0.115175 -0.664158  0.283156  2.465371  2.464723   
...        ...       ...       ...       ...       ...       ...       ...   
8446  1.205687  0.151377  0.686321 -0.877934  0.580576  0.869105  0.867984   
8520  3.776403  0.889420  0.226881 -0.446243  0.251720  4.557103  4.557758   
8538  1.175951  0.064096  0.802002 -0.815944  0.392444  1.495679  1.495301   
8611  1.290370  0.065288  0.432754 -0.837178  0.594740  2.826795  2.826380   
8678  1.099477  0.184350  0.241693 -0.163322  0.887362  3.306718  3.308711   
8720  3.552424  0.762272  0.473483 -0.561353  0.844441  1.769267  1.769261   
8762  0.905549  0.189462  0.298044 -0.288561  0.548041  3.543704  3.543562   
8820  3.958628  0.548906  0.445080 -0.860554  0.666274  0.624744  0.624526   
8842  2.776495  0.917994  0.159273 -0.423628  0.754629  3.542049  3.547850   
8850  3.639569  0.600122  0.629324 -0.779109  0.169405  3.282074  3.259574   
8910  2.489234  0.065984  0.740126 -0.596792  0.585903  3.377463  3.388483   
8916  1.239213  0.670149  0.586313 -0.254686  0.682302  3.072295  3.072952   
8943  2.731607  0.399149  0.602721 -0.428780  0.890472  1.470961  1.471221   
8944  1.927868  0.117462  0.267504 -0.542869  0.872997  1.656671  1.655451   
8994  4.421066  0.943476  0.411266 -0.864567  0.380249  3.047841  3.043822   
9015  4.843069  0.867038  0.471371 -0.448384  0.498801  4.293350  4.292214   
9084  4.734206  0.129814  0.757364 -0.302855  0.691647  2.990356  2.990514   
9166  2.502625  0.441648  0.942278 -0.573841  0.477713  2.994926  2.993046   
9194  1.059523  0.843116  0.771442 -0.512054  0.247357  2.603085  2.603222   
9236  4.764047  0.536987  0.475651

In [33]:
example = solved[solved.index==567]
example

Ik     Ivbar       Iv0      Irho    Isigma        Ok        Rk  \
567  2.003108  0.766503  0.278598 -0.606551  0.217312  0.819289  0.819279   

        Ovbar     Rvbar       Ov0  ...        time  iteration  pv  jac  \
567  0.452754  0.452759  0.063848  ...    0.430497         30  33   30   

     lin_sys            e0            e*        Je            Dp  count  
567       32  1.122818e+07  3.971408e-13  0.000003  1.156420e-07      1  

[1 rows x 26 columns]

In [34]:
example.values

array([[ 2.00310794e+00,  7.66502906e-01,  2.78598016e-01,
        -6.06551157e-01,  2.17311675e-01,  8.19289377e-01,
         8.19279086e-01,  4.52754204e-01,  4.52758708e-01,
         6.38483161e-02,  6.38483542e-02, -7.18027819e-01,
        -7.18027981e-01,  7.22171706e-01,  7.22171617e-01,
         6.00000000e+00,  4.30497000e-01,  3.00000000e+01,
         3.30000000e+01,  3.00000000e+01,  3.20000000e+01,
         1.12281824e+07,  3.97140758e-13,  2.59803814e-06,
         1.15641984e-07,  1.00000000e+00]])

In [40]:
np.abs(example['Ik'] - example['Rk'])

567    1.183829
dtype: float64

In [41]:
np.abs(example['Ivbar'] - example['Rvbar'])

567    0.313744
dtype: float64

In [42]:
np.abs(example['Iv0'] - example['Rv0'])

567    0.21475
dtype: float64

In [43]:
np.abs(example['Isigma'] - example['Rsigma'])

567    0.50486
dtype: float64

In [44]:
np.abs(example['Irho'] - example['Rrho'])

567    0.111477
dtype: float64

In [45]:
realPara = (example[['Rk', 'Rvbar', 'Rv0','Rrho', 'Rsigma']])
realPara.columns = ['k', 'vbar', 'v0', 'rho', 'sigma']
realPara.reset_index(drop=True, inplace=True)
newPara = pd.DataFrame(index=range(31), columns=realPara.columns)
for i in range(31):
    for name in realPara.columns:
        newPara.iloc[i][name] = realPara.iloc[0][name]
newPara

k      vbar         v0       rho     sigma
0   0.819279  0.452759  0.0638484 -0.718028  0.722172
1   0.819279  0.452759  0.0638484 -0.718028  0.722172
2   0.819279  0.452759  0.0638484 -0.718028  0.722172
3   0.819279  0.452759  0.0638484 -0.718028  0.722172
4   0.819279  0.452759  0.0638484 -0.718028  0.722172
5   0.819279  0.452759  0.0638484 -0.718028  0.722172
6   0.819279  0.452759  0.0638484 -0.718028  0.722172
7   0.819279  0.452759  0.0638484 -0.718028  0.722172
8   0.819279  0.452759  0.0638484 -0.718028  0.722172
9   0.819279  0.452759  0.0638484 -0.718028  0.722172
10  0.819279  0.452759  0.0638484 -0.718028  0.722172
11  0.819279  0.452759  0.0638484 -0.718028  0.722172
12  0.819279  0.452759  0.0638484 -0.718028  0.722172
13  0.819279  0.452759  0.0638484 -0.718028  0.722172
14  0.819279  0.452759  0.0638484 -0.718028  0.722172
15  0.819279  0.452759  0.0638484 -0.718028  0.722172
16  0.819279  0.452759  0.0638484 -0.718028  0.722172
17  0.819279  0.452759  0.0638484 -0.718028  0.722172
18  0.819279  0.452759  0.0638484 -0.718028  0.722172
19  0.819279  0.452759  0.0638484 -0.718028  0.722172
20  0.819279  0.452759  0.0638484 -0.718028  0.722172
21  0.819279  0.452759  0.0638484 -0.718028  0.722172
22  0.819279  0.452759  0.0638484 -0.718028  0.722172
23  0.819279  0.452759  0.0638484 -0.718028  0.722172
24  0.819279  0.452759  0.0638484 -0.718028  0.722172
25  0.819279  0.452759  0.0638484 -0.718028  0.722172
26  0.819279  0.452759  0.0638484 -0.718028  0.722172
27  0.819279  0.452759  0.0638484 -0.718028  0.722172
28  0.819279  0.452759  0.0638484 -0.718028  0.722172
29  0.819279  0.452759  0.0638484 -0.718028  0.722172
30  0.819279  0.452759  0.0638484 -0.718028  0.722172

In [47]:
paraRout = pd.read_csv("/home/lin/git/summerProject/paraRout")
paraRout

k      vbar        v0       rho     sigma
0   2.003108  0.766503  0.278598 -0.606551  0.217312
1   1.994029  0.724699  0.189030 -0.610187  0.228518
2   1.982846  0.677274  0.140961 -0.611728  0.235546
3   1.970775  0.626121  0.111046 -0.611977  0.241220
4   1.958803  0.573471  0.089061 -0.611404  0.246896
5   1.948925  0.527419  0.067376 -0.610923  0.253178
6   1.944743  0.506576  0.042040 -0.612459  0.258198
7   1.941752  0.490938  0.022661 -0.613929  0.261750
8   1.938261  0.471839  0.007217 -0.614936  0.265345
9   1.934198  0.448370 -0.009117 -0.616059  0.269575
10  1.930017  0.422237 -0.025356 -0.617622  0.274013
11  1.925383  0.390267 -0.033610 -0.619679  0.279294
12  1.919578  0.345077 -0.025009 -0.623126  0.287150
13  1.914692  0.294875 -0.007045 -0.624905  0.292908
14  1.906295  0.215047  0.037228 -0.632205  0.309901
15  1.900410  0.180697  0.053501 -0.630926  0.337019
16  1.898877  0.188379  0.050549 -0.615934  0.361106
17  1.893367  0.196327  0.050899 -0.608160  0.424227
18  1.878629  0.214886  0.053882 -0.642145  0.545086
19  1.844444  0.245552  0.059049 -0.699240  0.696172
20  1.768882  0.272215  0.062338 -0.719810  0.788244
21  1.598893  0.291626  0.063138 -0.722865  0.790735
22  1.376840  0.317133  0.063442 -0.722299  0.773212
23  1.149316  0.353749  0.063754 -0.721801  0.756365
24  1.005975  0.389744  0.063915 -0.721154  0.745035
25  0.879581  0.426635  0.063927 -0.719500  0.730871
26  0.817866  0.452653  0.063948 -0.718808  0.724791
27  0.814098  0.454967  0.063864 -0.718079  0.722034
28  0.819401  0.452681  0.063847 -0.718019  0.722150
29  0.818976  0.452886  0.063849 -0.718030  0.722160
30  0.819289  0.452755  0.063848 -0.718028  0.722172

In [48]:
routs = np.abs(paraRout - newPara)/np.abs(newPara)

In [49]:
%matplotlib tk

In [50]:
plt.semilogy(routs['k'], 'rX-')
plt.semilogy(routs['vbar'], 'bX-')
plt.semilogy(routs['v0'], 'kX-')
plt.semilogy(routs['rho'], 'gX-')
plt.semilogy(routs['sigma'], 'mX-')
plt.legend([r'$|k_k - k^{\star}|/|k^{\star}|$', r'$|\overline{\upsilon}_k - \overline{\upsilon}^{\star}|/|\overline{\upsilon}^{\star}|$', r'$|(\upsilon_0)_k - \upsilon_0^{\star}|/|\upsilon_0^{\star}|$',r'$|\rho_k - \rho^{\star}|/|\rho^{\star}|$',r'$|\sigma_k - \sigma^{\star}|/|\sigma^{\star}|$',], fontsize=22)
plt.xlabel('Index of iteration k', fontsize=24)
plt.ylabel('Nomalized differences between parameters found and targets', fontsize=24)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.grid()

In [54]:
residual = np.array([11228182.46038808,807255.2860647117,76039.65750674544,10062.25865084798,1887.359525438133,351.3059154344626,49.09839337737781,10.14481475124527,3.317012356056412,1.152402586648755,0.4177379994440593,0.2055414882174497,0.1282323013866701,0.08938729119401917,0.03267351837427038,0.02753496116476249,0.02170500399809178,0.01789866338104146,0.0108093724732074,0.004463637920357317,0.001246749982923448,0.000733681009537488,0.0005813803495587621,0.0005499026977308425,0.0001869581706586826,0.0001337921316549374,1.328981933037579e-05,6.953217715155133e-08,1.436982211690292e-09,2.082707307407935e-10,3.971677980382377e-13])

In [55]:
plt.semilogy(residual, 'bX-.')
plt.legend(['Reduction path of the objective function'], fontsize=22)
plt.xlabel('Index of iteration k', fontsize=24)
plt.ylabel('Value of the objective function', fontsize=24)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.grid()

In [56]:
realSPX = np.array([0.07478998780360964,0.1511881858006229,0.2027213809295823,0.2410147787627178,0.2731537190898699,0.3015950796032961,0.3634066696340293,0.4259388798643055,0.03423046264597641,0.05564391048588092,0.07821984090287659,0.099843150859326,0.1197462338377685,0.1379057817951416,0.1810112295762004,0.2187702577360547,0.01335175190303648,0.02636982030737595,0.03824713876862126,0.0496783014582497,0.06059723482555364,0.07117410881843453,0.1020129531561916,0.1289858583611486,5.507656245541976e-06,0.0003417334933978206,0.001793873971183487,0.004031474194149178,0.008600842548238147,0.01362447696797399,0.03324075369386573,0.05432814885255527,-3.810543297612796e-08,2.314515999204069e-06,4.939701354645699e-05,0.0002662664419762034,0.0008058353744827404,0.001794209495300502,0.008420466884001467,0.01913449284155004])

In [57]:
realSPX.shape

(40,)

In [58]:
realVIX = np.array([0.4361447852517755,0.4361285192330442,0.4361100410116878,0.4360911262154472,0.4360737204975733,0.4401700049222158,0.4401473105482878,0.4401212915991083,0.4400943990480715,0.4400694237215474,0.444095252384773,0.444067741566241,0.4440359772754752,0.4440029019018689,0.4439719673173388,0.448990974997294,0.4489584442123633,0.4489206007818745,0.4488808829620785,0.4488434563586114,0.4641372127842907,0.4640924073448026,0.4640392826533965,0.4639823989716804,0.4639277683211129,0.4776670574651534,0.4776132479141628,0.4775485079437879,0.4774781137667365,0.4774095149226167])

In [59]:
realVIX.shape

(30,)

In [64]:
initialSPX = np.array([0.09992093840981257,0.1781617982807032,0.2329235066714602,0.2749930226235151,0.3106782873547143,0.3422820828275765,0.4136692872971223,0.4799118705242865,0.06709033572913849,0.1030770804774587,0.1363788848334239,0.1667389423064116,0.1942112806390227,0.2191460100470349,0.2801283189375107,0.3313237149002883,0.04678646016073475,0.07706737451786527,0.1026386167084481,0.1257976614788078,0.1470885834874019,0.1669809914495011,0.2208814395382606,0.2660901298496009,0.00805724474535678,0.02619998314958867,0.04594411507825658,0.06353266005681651,0.0845012973891318,0.1029888528928549,0.1555681389458044,0.2010274887932842,0.00113129600711326,0.008799144330690551,0.02058895127311239,0.0343790256400592,0.04911691405801335,0.06425633203050402,0.1107907741822713,0.1531136597025941])

In [65]:
initialVIX = np.array([0.7497088142563657,0.7496925794246937,0.7496741366318193,0.7496552581010384,0.749637885755193,0.7544871438544895,0.7544644584834362,0.7544384498561026,0.754411567973601,0.7543866025551501,0.7590845992667851,0.759057078822633,0.7590253034180673,0.7589922164719897,0.7589612710640637,0.7646273075502549,0.7645947675448533,0.764556913388064,0.7645171843106657,0.7644797470989914,0.7807823437948596,0.7807375271756094,0.7806843892287504,0.7806274913537966,0.7805728470723017,0.7939488285269251,0.7938950067276593,0.7938302520211628,0.7937598418211995,0.7936912273630572])

In [60]:
optSPX = np.array([0.07478998330825991,0.1511881809624669,0.2027213742904438,0.2410147693292858,0.2731537060320192,0.3015950621576541,0.3634066339837972,0.4259388229055147,0.03423045697801266,0.05564390453620619,0.07821983386961903,0.09984314121849809,0.1197462200079833,0.1379057622601254,0.1810111849754902,0.2187701777850605,0.01335174762510088,0.0263698169715359,0.03824713629624694,0.0496782984407956,0.06059722951085358,0.07117409936709045,0.1020129208234652,0.1289857908825274,5.507653235168098e-06,0.0003417335484702847,0.001793874618338194,0.004031475693787042,0.008600844949581476,0.01362447892781697,0.03324074348211809,0.05432811081199039,-3.810543297612796e-08,2.314515445320785e-06,4.939699886146426e-05,0.0002662663642584691,0.0008058351466696318,0.001794208949200881,0.00842046207863016,0.01913447334959481])

In [61]:
optVIX = np.array([0.4361444591264983,0.4361281931076638,0.4361097148861902,0.4360908000898298,0.4360733943718457,0.4401696681720964,0.4401469737981951,0.4401209548490461,0.4400940622980407,0.440069086971546,0.4440949049733128,0.4440673941548383,0.4440356298641388,0.4440025544906016,0.4439716199061359,0.4489906132256151,0.4489580824407348,0.4489202390103048,0.4488805211905705,0.4488430945871615,0.4641367984359148,0.4640919929964292,0.464038868305026,0.4639819846233131,0.4639273539727485,0.4776665850977025,0.4776127755466941,0.477548035576298,0.4774776413992233,0.4774090425550807])

In [66]:
diffInitialSPX = np.abs(realSPX - initialSPX)

In [67]:
diffInitialVIX = np.abs(realVIX - initialVIX)

In [68]:
diffOptSPX = np.abs(realSPX - optSPX)
diffOptVIX = np.abs(realVIX - optVIX)

In [69]:
VIXstrike = np.array([0.07660333466800909, 0.07823036262505452, 0.08007866879151475,
                      0.08197064388101638, 0.08371167160297435, 0.07528231789011931,
                      0.07755350918528185, 0.08015741494276396, 0.08284874840358378,
                      0.0853482112450969,  0.07430112345712658, 0.077055734551228,
                      0.08023623852982013, 0.08354801898792094, 0.08664544590808211,
                      0.0732872469748735,  0.07654634796281677, 0.08033769704753065,
                      0.08431683207193616, 0.08806642128491488, 0.07084911309063555,
                      0.07534553012964565, 0.08067681958626018, 0.08638533974549638,
                      0.0918677586016848,  0.06910110193769552, 0.07450988995253548,
                      0.08101737363349071, 0.08809320258894406, 0.0949885695945464])

In [70]:
VIXexp = np.array([7, 7, 7, 7, 7, 14, 14, 14, 14, 14, 21, 21, 21, 21, 21, 30, 30, 30, 30, 30, 60, 60, 60, 60, 60, 90, 90, 90, 90, 90])

In [71]:
SPXstrike = np.array([0.9371, 0.8603, 0.8112, 0.7760, 0.7470, 0.7216, 0.6699,
                      0.6137, 0.9956, 0.9868, 0.9728, 0.9588, 0.9464, 0.9358,
                      0.9175, 0.9025, 1.0427, 1.0463, 1.0499, 1.0530, 1.0562,
                      1.0593, 1.0663, 1.0766, 1.2287, 1.2399, 1.2485, 1.2659,
                      1.2646, 1.2715, 1.2859, 1.3046, 1.3939, 1.4102, 1.4291,
                      1.4456, 1.4603, 1.4736, 1.5005, 1.5328])
SPXexp = np.array([30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360])

In [77]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.dist=10
for i in range(30):
    ax.plot(np.array([VIXstrike[i], VIXstrike[i]]), np.array([VIXexp[i], VIXexp[i]]), np.array([diffInitialVIX.min()-0.0005, diffInitialVIX[i]]), 'y-.', alpha=0.5)
ax.scatter(VIXstrike, VIXexp, diffInitialVIX, s = 30, depthshade=False)
ax.set_xlabel('Strikes of VIX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of VIX options', fontsize=24, labelpad=22)
ax.set_zlabel('Errors', fontsize=24, labelpad=45)
plt.xticks(fontsize=20)
plt.yticks([7, 14, 21, 30, 60, 90], fontsize=20)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=20)
plt.grid()

In [80]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.dist=10
ax.scatter(VIXstrike, VIXexp, diffOptVIX, s = 30, depthshade=False)
for i in range(30):
    ax.plot(np.array([VIXstrike[i], VIXstrike[i]]), np.array([VIXexp[i], VIXexp[i]]), np.array([diffOptVIX.min()-0.00000001, diffOptVIX[i]]), 'y-.', alpha=0.5)
ax.set_xlabel('Strikes of VIX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of VIX options', fontsize=24, labelpad=22)
ax.set_zlabel('Errors', fontsize=24, labelpad=20)
plt.xticks(fontsize=20)
plt.yticks([7, 14, 21, 30, 60, 90], fontsize=20)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=5)
plt.grid()


In [85]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(SPXstrike, SPXexp, diffInitialSPX, s = 30, depthshade=False)
for i in range(40):
    ax.plot(np.array([SPXstrike[i], SPXstrike[i]]), np.array([SPXexp[i], SPXexp[i]]), np.array([diffInitialSPX.min()-0.01, diffInitialSPX[i]]), 'y-.', alpha=0.5)
ax.set_xlabel('Strikes of SPX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of SPX options', fontsize=24, labelpad=22)
ax.set_zlabel('Errors', fontsize=24, labelpad=40)
plt.xticks(fontsize=20)
plt.yticks([30, 60, 90, 120, 150, 180, 270, 360], fontsize=15)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=20)
plt.grid()

In [84]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(SPXstrike, SPXexp, diffOptSPX, s = 30, depthshade=False)
for i in range(40):
    ax.plot(np.array([SPXstrike[i], SPXstrike[i]]), np.array([SPXexp[i], SPXexp[i]]), np.array([diffOptSPX.min()-0.00000001, diffOptSPX[i]]), 'y-.', alpha=0.5)
ax.set_xlabel('Strikes of SPX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of SPX options', fontsize=24, labelpad=22)
ax.set_zlabel('Errors', fontsize=24, labelpad=20)
plt.xticks(fontsize=20)
plt.yticks([30, 60, 90, 120, 150, 180, 270, 360], fontsize=15)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=10)
plt.grid()