In [118]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.special import erf
from scipy.stats import norm
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
#%matplotlib tk

In [119]:
result = pd.read_csv("/home/lin/git/summerProject/HestonNumerical")

In [120]:
result[['time', 'iteration', 'pv', 'jac', 'lin_sys', 'e0', 'e*', 'Je', 'Dp', 'count','count2', 'count7']].describe()

time   iteration          pv        jac     lin_sys           e0  \
count  100.000000  100.000000  100.000000  100.00000  100.000000   100.000000   
mean     1.181225   95.090000  145.340000    9.85000   95.090000    93.010585   
std      2.007840   79.798875  119.047586    7.85651   79.798875   304.770390   
min      0.166682   16.000000   27.000000    2.00000   16.000000     0.093713   
25%      0.366984   37.750000   58.750000    4.00000   37.750000     9.726969   
50%      0.632085   68.000000  104.000000    7.00000   68.000000    33.825097   
75%      1.352011  117.500000  178.500000   12.00000  117.500000    81.054058   
max     18.611459  300.000000  451.000000   30.00000  300.000000  2986.169908   

                 e*            Je          Dp      count     count2  count7  
count  1.000000e+02  1.000000e+02  100.000000  100.00000  100.00000   100.0  
mean   2.508816e+01  3.174204e-04    0.000030    1.20000    0.20000     0.0  
std    2.508815e+02  7.949473e-04    0.000118    1.03475    1.03475     0.0  
min    7.357102e-15  2.651213e-12    0.000000    1.00000    0.00000     0.0  
25%    1.182947e-11  9.775510e-11    0.000000    1.00000    0.00000     0.0  
50%    7.582908e-11  9.394221e-05    0.000001    1.00000    0.00000     0.0  
75%    6.464456e-08  2.395363e-04    0.000014    1.00000    0.00000     0.0  
max    2.508815e+03  6.679881e-03    0.001067   10.00000    9.00000     0.0

In [121]:
result[['Ok', 'Rk', 'Ovbar', 'Rvbar', 'Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma']].head(50)

Ok        Rk     Ovbar     Rvbar        Ov0       Rv0      Orho  \
0   1.431937  1.091920  0.406948  0.462785   0.262636  0.247063 -0.106159   
1   3.590508  3.590477  0.887392  0.887393   0.524235  0.524236 -0.705128   
2   4.921472  4.921476  0.728020  0.728020   0.115418  0.115417 -0.818125   
3   1.260344  2.770353  0.301588  0.337130   0.455041  0.494579 -0.140067   
4   1.066167  1.064144  0.669544  0.669610   0.616586  0.616589 -0.218026   
5   4.799164  4.799340  0.183336  0.183336   0.417883  0.417890 -0.621003   
6   2.645465  2.643943  0.232924  0.232925   0.861802  0.861506 -0.208087   
7   2.535666  2.535351  0.888467  0.888507   0.243728  0.243724 -0.606191   
8   3.659975  3.659930  0.908972  0.908973   0.310382  0.310385 -0.665228   
9   2.868863  2.862443  0.108685  0.108674   0.490736  0.490049 -0.456819   
10  2.338012  2.478765  0.791750  0.775985   0.239432  0.240367 -0.644450   
11  4.229264  4.229186  0.123564  0.123564   0.616622  0.616615 -0.727092   
12  0.642903  0.550923  0.942566  0.934912   0.778857  0.787753 -0.607774   
13  3.890974  3.888232  0.620083  0.620087   0.588384  0.588395 -0.229350   
14  3.005682  3.005761  0.334406  0.334407   0.525691  0.525693 -0.162611   
15  3.543782  3.543066  0.705755  0.705748   0.900297  0.900278 -0.375054   
16  0.269849  0.567278 -5.106201  0.628681  19.546533  0.876063 -0.397528   
17  0.967094  0.967088  0.748290  0.748292   0.099750  0.099751 -0.766946   
18  1.990300  1.990287  0.938193  0.938195   0.051490  0.051492 -0.250621   
19  1.346640  1.066698  0.897078  0.908626   0.801246  0.804291 -0.632403   
20  2.970750  2.961387  0.208375  0.208377   0.439333  0.438717 -0.300124   
21  3.871653  3.871632  0.663499  0.663499   0.082729  0.082731 -0.227806   
22  4.771131  4.771207  0.608942  0.608941   0.066156  0.066150 -0.363245   
23  1.271320  1.271207  0.895727  0.895753   0.279453  0.279462 -0.561421   
24  3.649065  3.649060  0.891717  0.891717   0.375875  0.375875 -0.521951   
25  2.440689  3.702040  0.392831  0.394539   0.451261  0.463786 -0.856836   
26  2.111777  2.063713  0.508234  0.508692   0.806318  0.800905 -0.276412   
27  3.683054  3.679076  0.285610  0.285601   0.390621  0.390530 -0.573271   
28  2.683099  2.914377  0.410136  0.413223   0.890930  0.920219 -0.117924   
29  3.535343  3.535361  0.678615  0.678614   0.222786  0.222785 -0.709875   
30  4.507505  4.664764  0.437745  0.437401   0.785573  0.798130 -0.633639   
31  6.980375  3.505844  0.554501  0.564424   0.411357  0.447182 -0.541464   
32  3.867282  3.974136  0.488363  0.488013   0.671630  0.677296 -0.288322   
33  4.641662  4.641136  0.789053  0.789060   0.257205  0.257243 -0.198360   
34  0.989964  0.984825  0.139547  0.139879   0.360786  0.360119 -0.493473   
35  1.200810  1.218109  0.184725  0.184326   0.390818  0.392547 -0.236637   
36  2.867490  2.849966  0.299437  0.299478   0.579672  0.578176 -0.675136   
37  4.455426  4.455769  0.130867  0.130868   0.425098  0.425117 -0.401988   
38  0.518068  0.845698  0.527346  0.479877   0.280002  0.264217 -0.487098   
39  4.697367  4.697796  0.181577  0.181576   0.122293  0.122290 -0.568540   
40  3.193075  3.200597  0.183953  0.183909   0.944206  0.945861 -0.739228   
41  2.014143  2.004380  0.180195  0.180408   0.652029  0.650171 -0.766919   
42  2.561121  2.561206  0.190282  0.190286   0.649369  0.649376 -0.398687   
43  3.047318  3.047822  0.430300  0.430297   0.313751  0.313739 -0.576742   
44  2.129071  0.970607  0.752581  0.800040   0.619544  0.642734 -0.321334   
45  4.263937  4.263690  0.349637  0.349635   0.532368  0.532361 -0.768798   
46  3.522344  3.522417  0.834158  0.834155   0.154053  0.154046 -0.147968   
47  1.246969  1.293890  0.857329  0.857520   0.589909  0.584743 -0.295440   
48  4.653349  4.826463  0.245733  0.245669   0.736604  0.754227 -0.618460   
49  1.109697  0.975031  0.440004  0.374871   0.673837  0.697284 -0.373478   

        Rrho    Osigma    Rsigma  
0  -0.643092 -0.116216  0.891224  
1  -0.623135

In [122]:
result.columns

Index(['Ik', 'Ivbar', 'Iv0', 'Irho', 'Isigma', 'Ok', 'Rk', 'Ovbar', 'Rvbar',
       'Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma', 'stopped_by', 'time',
       'iteration', 'pv', 'jac', 'lin_sys', 'e0', 'e*', 'Je', 'Dp', 'count',
       'count2', 'count7'],
      dtype='object')

In [123]:
result['stopped_by'].unique() #3, itmax, 1 small gradient, 5 increase mu

array([1, 6, 3])

In [124]:
solved = result[result['stopped_by'] == 6]
solved.count().unique()

array([68])

In [125]:
solved.count().unique()/result.count().unique()

array([0.68])

In [126]:
solved_first_time = solved[solved['count'] == 1]
solved_first_time.count().unique()

array([66])

In [127]:
DP = result[result['stopped_by'] == 2]
DP.count().unique()

array([0])

In [128]:
invalid_value = result[result['stopped_by'] == 7]
invalid_value.count().unique()

array([0])

In [129]:
DP

Empty DataFrame
Columns: [Ik, Ivbar, Iv0, Irho, Isigma, Ok, Rk, Ovbar, Rvbar, Ov0, Rv0, Orho, Rrho, Osigma, Rsigma, stopped_by, time, iteration, pv, jac, lin_sys, e0, e*, Je, Dp, count, count2, count7]
Index: []

[0 rows x 28 columns]

In [130]:
invalid_value

Empty DataFrame
Columns: [Ik, Ivbar, Iv0, Irho, Isigma, Ok, Rk, Ovbar, Rvbar, Ov0, Rv0, Orho, Rrho, Osigma, Rsigma, stopped_by, time, iteration, pv, jac, lin_sys, e0, e*, Je, Dp, count, count2, count7]
Index: []

[0 rows x 28 columns]

In [131]:
itmax = result[result['stopped_by'] == 3]
itmax.count().unique()

array([6])

In [132]:
smalJac = result[result['stopped_by'] == 1]
smalJac.count().unique()

array([26])

In [133]:
solved['time'].describe()

count    68.000000
mean      0.677949
std       0.572507
min       0.166682
25%       0.331215
50%       0.514135
75%       0.785755
max       3.320020
Name: time, dtype: float64

In [134]:
solved_first_time['time'].describe()

count    66.000000
mean      0.615086
std       0.437620
min       0.166682
25%       0.331208
50%       0.508642
75%       0.747086
max       2.175443
Name: time, dtype: float64

In [135]:
solved_first_time['iteration'].describe()

count     66.000000
mean      62.000000
std       45.427542
min       16.000000
25%       28.750000
50%       50.000000
75%       73.750000
max      241.000000
Name: iteration, dtype: float64

In [136]:
solved['iteration'].describe()

count     68.000000
mean      63.264706
std       45.340377
min       16.000000
25%       30.250000
50%       51.000000
75%       80.250000
max      241.000000
Name: iteration, dtype: float64

In [137]:
solved['pv'].describe()

count     68.000000
mean      98.161765
std       68.213583
min       27.000000
25%       50.000000
50%       82.000000
75%      121.250000
max      367.000000
Name: pv, dtype: float64

In [138]:
solved['jac'].describe()

count    68.000000
mean      6.779412
std       4.583701
min       2.000000
25%       3.750000
50%       6.000000
75%       8.000000
max      25.000000
Name: jac, dtype: float64

In [139]:
solved[['Ik', 'Ivbar', 'Iv0', 'Irho', 'Isigma', 'Ok', 'Rk', 'Ovbar', 'Rvbar',
       'Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma', 'stopped_by', 'time']].head()

Ik     Ivbar       Iv0      Irho    Isigma        Ok        Rk  \
1  3.929891  0.092718  0.345411 -0.705128  0.378805  3.590508  3.590477   
2  2.649793  0.297416  0.199856 -0.818125  0.104508  4.921472  4.921476   
4  3.434264  0.663212  0.398953 -0.218026  0.811018  1.066167  1.064144   
5  4.824928  0.229781  0.616342 -0.621003  0.772766  4.799164  4.799340   
6  4.485418  0.195979  0.378805 -0.208087  0.459777  2.645465  2.643943   

      Ovbar     Rvbar       Ov0       Rv0      Orho      Rrho    Osigma  \
1  0.887392  0.887393  0.524235  0.524236 -0.705128 -0.623135  0.681029   
2  0.728020  0.728020  0.115418  0.115417 -0.818125 -0.807766  0.442770   
4  0.669544  0.669610  0.616586  0.616589 -0.218026 -0.680330  0.850416   
5  0.183336  0.183336  0.417883  0.417890 -0.621003 -0.551919  0.489785   
6  0.232924  0.232925  0.861802  0.861506 -0.208087 -0.213617  0.412970   

     Rsigma  stopped_by      time  
1  0.681072           6  0.227517  
2  0.442770           6  0.312234  
4  0.849715           6  3.320020  
5  0.489663           6  0.193403  
6  0.419282           6  0.453212

In [140]:
solved[['Ik', 'Ivbar', 'Iv0', 'Irho', 'Isigma', 'Ok', 'Rk', 'Ovbar', 'Rvbar',
       'Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma', 'stopped_by', 'time']].describe()

Ik      Ivbar        Iv0       Irho     Isigma         Ok  \
count  68.000000  68.000000  68.000000  68.000000  68.000000  68.000000   
mean    2.964713   0.459248   0.499564  -0.496826   0.436661   2.974142   
std     1.367873   0.244459   0.255593   0.221366   0.265953   1.205044   
min     0.550144   0.080819   0.073706  -0.889944   0.053782   0.651169   
25%     1.986486   0.256397   0.269227  -0.686655   0.182439   2.008183   
50%     2.902819   0.414170   0.475093  -0.507712   0.410088   3.026500   
75%     4.206144   0.671719   0.701832  -0.299179   0.689068   3.858459   
max     4.897572   0.900007   0.940426  -0.114601   0.851408   4.921472   

              Rk      Ovbar      Rvbar        Ov0        Rv0       Orho  \
count  68.000000  68.000000  68.000000  68.000000  68.000000  68.000000   
mean    2.968001   0.488623   0.488597   0.475299   0.474963  -0.496826   
std     1.209489   0.260898   0.260912   0.237198   0.237036   0.221366   
min     0.673969   0.103217   0.103141   0.051490   0.051492  -0.889944   
25%     2.000857   0.233365   0.233381   0.298612   0.298615  -0.686655   
50%     3.026791   0.489296   0.488642   0.432215   0.431917  -0.507712   
75%     3.859046   0.691032   0.691040   0.650034   0.649575  -0.299179   
max     4.921476   0.938193   0.938195   0.944206   0.945861  -0.114601   

            Rrho     Osigma     Rsigma  stopped_by       time  
count  68.000000  68.000000  68.000000        68.0  68.000000  
mean   -0.499150   0.458418   0.514053         6.0   0.677949  
std     0.222014   0.327988   0.244039         0.0   0.572507  
min    -0.872669  -0.651177   0.053437         6.0   0.166682  
25%    -0.653508   0.302094   0.326301         6.0   0.331215  
50%    -0.483500   0.473919   0.484823         6.0   0.514135  
75%    -0.281494   0.691907   0.721039         6.0   0.785755  
max    -0.123484   0.926046   0.936888         6.0   3.320020

In [141]:
solved[['Orho', 'Rrho', 'Osigma', 'Rsigma']].iloc[:1000]

Orho      Rrho    Osigma    Rsigma
1  -0.705128 -0.623135  0.681029  0.681072
2  -0.818125 -0.807766  0.442770  0.442770
4  -0.218026 -0.680330  0.850416  0.849715
5  -0.621003 -0.551919  0.489785  0.489663
6  -0.208087 -0.213617  0.412970  0.419282
7  -0.606191 -0.827138  0.822697  0.824774
8  -0.665228 -0.511548 -0.422609  0.422626
9  -0.456819 -0.645639  0.868519  0.874971
11 -0.727092 -0.270837  0.399860  0.399941
13 -0.229350 -0.355022  0.155825  0.155693
14 -0.162611 -0.570495  0.437775  0.437763
15 -0.375054 -0.852130  0.464771  0.464391
17 -0.766946 -0.228219  0.317328  0.317320
18 -0.250621 -0.123484  0.490694  0.490687
20 -0.300124 -0.649932  0.793165  0.802586
21 -0.227806 -0.277334  0.637458  0.637360
22 -0.363245 -0.677497  0.098364  0.098325
23 -0.561421 -0.199079  0.194100  0.194075
24 -0.521951 -0.464058  0.266397  0.266396
26 -0.276412 -0.363547  0.515342  0.618587
27 -0.573271 -0.286086  0.471268  0.472549
29 -0.709875 -0.376697  0.176639  0.176639
33 -0.198360 -0.819617  0.636572  0.636363
34 -0.493473 -0.706097  0.336451  0.347683
35 -0.236637 -0.439307 -0.651177  0.636165
36 -0.675136 -0.749516  0.874259  0.895884
37 -0.401988 -0.639754  0.782121  0.781742
39 -0.568540 -0.426542  0.916685  0.916844
40 -0.739228 -0.422192  0.808563  0.787574
41 -0.766919 -0.351759  0.567199  0.592024
..       ...       ...       ...       ...
54 -0.855354 -0.467131 -0.261219  0.261208
57 -0.591141 -0.365658  0.676038  0.719667
60 -0.258904 -0.578365  0.106674  0.106597
61 -0.473574 -0.836749  0.053440  0.053437
62 -0.124032 -0.263131 -0.064447  0.064467
63 -0.341112 -0.539125  0.753031  0.728003
64 -0.616277 -0.521040  0.132399  0.132380
65 -0.613101 -0.233828  0.926046  0.936888
68 -0.764535 -0.181975  0.823562  0.827025
70 -0.538692 -0.236982  0.304895  0.304545
71 -0.425400 -0.633683  0.655480  0.787284
72 -0.581605 -0.863433  0.861609  0.862074
73 -0.314868 -0.547287  0.691412  0.679127
74 -0.813719 -0.158284  0.391109  0.391060
75 -0.296342 -0.499868  0.124345  0.124338
76 -0.745084 -0.381495  0.450814  0.420989
79 -0.443393 -0.436041  0.480476  0.479983
81 -0.218963 -0.647128  0.476570  0.476530
83 -0.433966 -0.282881  0.811291  0.825286
84 -0.889944 -0.872669  0.423147  0.425155
86 -0.680188 -0.274900  0.293691  0.293631
87 -0.370762 -0.605474  0.533526  0.540176
88 -0.757840 -0.245585  0.463248  0.527838
89 -0.763465 -0.232034  0.310864  0.329295
91 -0.680497 -0.467073  0.195945  0.195618
93 -0.532444 -0.267108  0.679807  0.669966
94 -0.492208 -0.664239  0.391898  0.393980
95 -0.784849 -0.639689  0.594367  0.587063
98 -0.254205 -0.227084  0.693391  0.693288
99 -0.119434 -0.843122  0.757623  0.757613

[68 rows x 4 columns]

In [142]:
solved[solved['Orho'] * solved['Rrho'] < 0].count()

Ik            0
Ivbar         0
Iv0           0
Irho          0
Isigma        0
Ok            0
Rk            0
Ovbar         0
Rvbar         0
Ov0           0
Rv0           0
Orho          0
Rrho          0
Osigma        0
Rsigma        0
stopped_by    0
time          0
iteration     0
pv            0
jac           0
lin_sys       0
e0            0
e*            0
Je            0
Dp            0
count         0
count2        0
count7        0
dtype: int64

In [143]:
disIk = np.abs(solved['Ik'] - solved['Rk']).mean()
disIk

1.3183906895337623

In [144]:
disIvbar = np.abs(solved['Ivbar'] - solved['Rvbar']).mean()
disIvbar

0.2558779333368672

In [145]:
disIv0 = np.abs(solved['Iv0'] - solved['Rv0']).mean()
disIv0

0.27462763078127633

In [146]:
disIsigma = np.abs(solved['Isigma'] - solved['Rsigma']).mean()
disIsigma

0.30296408396301

In [147]:
disIrho = np.abs(solved['Irho'] - solved['Rrho']).mean()
disIrho

0.2815863438587717

In [148]:
disOk = np.abs(solved['Ok'] - solved['Rk']).mean()
disOk

0.010326950257866466

In [149]:
disOvbar = np.abs(solved['Ovbar'] - solved['Rvbar']).mean()
disOvbar

0.00018085173860372828

In [150]:
disOsigma = (np.abs(solved['Osigma']) - np.abs(solved['Rsigma'])).mean()
disOsigma

-0.005362150602090723

In [151]:
disOrho = (np.abs(solved['Orho']) - np.abs(solved['Rrho'])).mean()
disOrho

-0.0023247172468061823

In [152]:
disOv0 = np.abs(solved['Ov0'] - solved['Rv0']).mean()
disOv0

0.0005968327680037475

In [511]:
solved.describe()

Ik        Ivbar          Iv0         Irho       Isigma  \
count  8878.000000  8878.000000  8878.000000  8878.000000  8878.000000   
mean      2.839779     0.503683     0.497545    -0.499683     0.500484   
std       1.284128     0.256991     0.259553     0.231691     0.262699   
min       0.500264     0.050188     0.050074    -0.899970     0.050205   
25%       1.745381     0.285918     0.272610    -0.700868     0.269551   
50%       2.883985     0.504158     0.494616    -0.498099     0.502299   
75%       3.953441     0.723633     0.720725    -0.303795     0.728477   
max       4.999459     0.949942     0.949780    -0.100025     0.949989   

                Ok           Rk        Ovbar        Rvbar          Ov0  \
count  8878.000000  8878.000000  8878.000000  8878.000000  8878.000000   
mean      2.739604     2.739796     0.527108     0.527107     0.471986   
std       1.298493     1.299320     0.254642     0.254651     0.254691   
min       0.496902     0.500016     0.049931     0.050004     0.050294   
25%       1.613002     1.611194     0.313491     0.313498     0.250747   
50%       2.746302     2.745442     0.540362     0.540374     0.459177   
75%       3.862887     3.862522     0.746712     0.746671     0.684615   
max       4.999151     4.999669     0.949877     0.949916     0.949871   

          ...                pv          jac      lin_sys            e0  \
count     ...       8878.000000  8878.000000  8878.000000  8.878000e+03   
mean      ...         37.692273    31.298829    36.692273  5.867487e+08   
std       ...         32.416938    27.793118    32.416938  3.648078e+10   
min       ...          7.000000     6.000000     6.000000  9.027880e-05   
25%       ...         21.000000    18.000000    20.000000  5.483586e-02   
50%       ...         29.000000    23.000000    28.000000  1.610783e-01   
75%       ...         40.000000    32.000000    39.000000  8.840492e-01   
max       ...        438.000000   298.000000   437.000000  2.702254e+12   

                 e*            Je            Dp        count       count2  \
count  8.878000e+03  8.878000e+03  8.878000e+03  8878.000000  8878.000000   
mean   5.680224e-11  1.932932e-05  1.403808e-05     1.729106     0.713900   
std    3.019029e-11  1.469771e-04  5.171231e-05     4.041041     4.000047   
min    1.404184e-14  2.952350e-08  1.140932e-10     1.000000     0.000000   
25%    3.133322e-11  3.192143e-06  1.440642e-07     1.000000     0.000000   
50%    6.134655e-11  6.576944e-06  1.074532e-06     1.000000     0.000000   
75%    8.395727e-11  1.380609e-05  7.502298e-06     1.000000     0.000000   
max    9.999973e-11  8.891854e-03  2.009913e-03    96.000000    95.000000   

            count7  
count  8878.000000  
mean      0.015206  
std       0.145120  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       5.000000  

[8 rows x 28 columns]

In [512]:
solved[solved['iteration']==30]

Ik     Ivbar       Iv0      Irho    Isigma        Ok        Rk  \
77    1.490986  0.262491  0.769627 -0.634046  0.732472  3.939412  3.939334   
130   0.862139  0.617437  0.854700 -0.839130  0.826624  1.408607  1.411699   
247   3.011752  0.240952  0.639450 -0.456274  0.824212  1.132023  1.131482   
261   3.242873  0.295908  0.746932 -0.216498  0.633355  4.234708  4.235667   
340   4.740762  0.084700  0.317163 -0.287067  0.354950  0.867461  0.865188   
360   2.363923  0.903952  0.479018 -0.299017  0.200149  1.187901  1.187938   
361   3.102701  0.860408  0.305838 -0.289019  0.798743  3.391865  3.392061   
517   0.591684  0.091415  0.088138 -0.810682  0.648596  1.991238  1.992370   
525   2.803758  0.705094  0.104987 -0.258899  0.776825  3.561165  3.560733   
776   0.946217  0.175794  0.663288 -0.793941  0.907702  4.839112  4.837104   
890   1.390849  0.854273  0.060306 -0.674258  0.700752  0.795308  0.793752   
902   2.885987  0.498783  0.138190 -0.132373  0.612732  1.568369  1.567603   
952   1.199086  0.859351  0.775583 -0.839163  0.075104  1.005507  1.006498   
1238  0.787776  0.925597  0.658713 -0.439210  0.386505  4.235608  4.236910   
1246  2.913162  0.844372  0.803875 -0.800698  0.817108  4.791470  4.791647   
1400  2.181171  0.551733  0.594394 -0.529412  0.801392  2.444974  2.445753   
1590  4.119005  0.575243  0.882916 -0.300838  0.615366  2.545100  2.542643   
1715  4.211247  0.416518  0.937908 -0.170551  0.525438  3.484886  3.475469   
1725  0.578018  0.114977  0.716706 -0.164587  0.448189  3.910738  3.910143   
1807  4.903358  0.100255  0.848854 -0.831460  0.528851  2.832067  2.832045   
1934  3.519347  0.554042  0.871972 -0.116713  0.560661  3.034445  3.034247   
1965  3.453356  0.893040  0.607909 -0.660102  0.727647  1.674260  1.673704   
2052  1.922206  0.590528  0.218230 -0.525409  0.791255  3.838821  3.842953   
2087  1.665588  0.367576  0.075163 -0.829057  0.907249  1.048222  1.045290   
2151  3.909577  0.322359  0.347947 -0.763806  0.926002  1.997340  1.995754   
2334  4.183577  0.170375  0.506591 -0.323978  0.273353  4.775987  4.777225   
2387  2.863354  0.563177  0.403550 -0.608407  0.436304  1.134179  1.134167   
2490  3.395401  0.409588  0.837265 -0.668468  0.899582  4.512060  4.512456   
2495  2.725534  0.135441  0.108590 -0.174756  0.701373  2.049623  2.049763   
2500  3.062132  0.412211  0.664463 -0.398041  0.050736  1.195824  1.194385   
...        ...       ...       ...       ...       ...       ...       ...   
8425  1.891125  0.467710  0.063378 -0.566758  0.928079  4.557990  4.573883   
8441  1.310320  0.476216  0.225022 -0.695307  0.324511  4.645115  4.647010   
8516  0.776867  0.882152  0.631920 -0.350114  0.818174  1.785133  1.785527   
8623  1.944176  0.061393  0.130260 -0.552344  0.076121  4.571750  4.573423   
8637  1.185984  0.465853  0.116634 -0.322080  0.177325  3.636956  3.640084   
8640  4.646375  0.460946  0.799151 -0.645090  0.154201  1.771946  1.771162   
8767  0.634736  0.338245  0.756551 -0.664240  0.515631  3.330101  3.330801   
8807  1.956670  0.788694  0.060117 -0.382639  0.738019  1.323976  1.321059   
8828  2.142985  0.452549  0.404088 -0.614728  0.505104  2.155515  2.156163   
8916  2.099398  0.433959  0.158848 -0.651142  0.242730  1.007902  1.008031   
9054  2.828024  0.405842  0.904563 -0.678511  0.662005  0.817203  0.816335   
9059  4.304162  0.841990  0.053409 -0.213599  0.773405  4.953023  4.952795   
9063  1.121511  0.471722  0.642341 -0.425326  0.157186  4.543576  4.547543   
9100  4.064164  0.848629  0.799185 -0.725519  0.415512  1.499105  1.497905   
9123  1.371545  0.860111  0.607779 -0.831935  0.613099  1.851567  1.851357   
9139  2.470020  0.282589  0.394763 -0.584078  0.186925  0.636964  0.634268   
9295  2.134451  0.750317  0.599832 -0.613181  0.166276  3.128739  3.128066   
9351  4.251691  0.384572  0.518258 -0.582968  0.691124  2.960039  2.957119   
9406  4.524221  0.802070  0.458726 -0.355397  0.639489  4.793703  4.793976   
9411  2.819244  0.530403  0.877609

In [515]:
example = solved[solved.index==77]
example

Ik     Ivbar       Iv0      Irho    Isigma        Ok        Rk  \
77  1.490986  0.262491  0.769627 -0.634046  0.732472  3.939412  3.939334   

       Ovbar    Rvbar       Ov0   ...    pv  jac  lin_sys        e0  \
77  0.607111  0.60711  0.162443   ...    37   30       36  18.56264   

              e*        Je        Dp  count  count2  count7  
77  4.262171e-12  0.000013  0.000001      1       0       0  

[1 rows x 28 columns]

In [516]:
example.values

array([[ 1.49098603e+00,  2.62491155e-01,  7.69627337e-01,
        -6.34046495e-01,  7.32472281e-01,  3.93941155e+00,
         3.93933429e+00,  6.07110577e-01,  6.07109852e-01,
         1.62443176e-01,  1.62443977e-01, -5.51500600e-01,
        -5.51629288e-01,  3.50395904e-01,  3.50281522e-01,
         6.00000000e+00,  5.46694000e-01,  3.00000000e+01,
         3.70000000e+01,  3.00000000e+01,  3.60000000e+01,
         1.85626401e+01,  4.26217127e-12,  1.33558296e-05,
         1.34274732e-06,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [532]:
np.abs(example['Ik'] - example['Rk']).values

array([2.44834826])

In [533]:
np.abs(example['Ivbar'] - example['Rvbar']).values

array([0.3446187])

In [534]:
np.abs(example['Iv0'] - example['Rv0']).values

array([0.60718336])

In [535]:
np.abs(example['Isigma'] - example['Rsigma']).values

array([0.38219076])

In [536]:
np.abs(example['Irho'] - example['Rrho']).values

array([0.08241721])

In [537]:
realPara = (example[['Rk', 'Rvbar', 'Rv0','Rrho', 'Rsigma']])
realPara.columns = ['k', 'vbar', 'v0', 'rho', 'sigma']
realPara.reset_index(drop=True, inplace=True)
newPara = pd.DataFrame(index=range(31), columns=realPara.columns)
for i in range(31):
    for name in realPara.columns:
        newPara.iloc[i][name] = realPara.iloc[0][name]
newPara

k     vbar        v0       rho     sigma
0   3.93933  0.60711  0.162444 -0.551629  0.350282
1   3.93933  0.60711  0.162444 -0.551629  0.350282
2   3.93933  0.60711  0.162444 -0.551629  0.350282
3   3.93933  0.60711  0.162444 -0.551629  0.350282
4   3.93933  0.60711  0.162444 -0.551629  0.350282
5   3.93933  0.60711  0.162444 -0.551629  0.350282
6   3.93933  0.60711  0.162444 -0.551629  0.350282
7   3.93933  0.60711  0.162444 -0.551629  0.350282
8   3.93933  0.60711  0.162444 -0.551629  0.350282
9   3.93933  0.60711  0.162444 -0.551629  0.350282
10  3.93933  0.60711  0.162444 -0.551629  0.350282
11  3.93933  0.60711  0.162444 -0.551629  0.350282
12  3.93933  0.60711  0.162444 -0.551629  0.350282
13  3.93933  0.60711  0.162444 -0.551629  0.350282
14  3.93933  0.60711  0.162444 -0.551629  0.350282
15  3.93933  0.60711  0.162444 -0.551629  0.350282
16  3.93933  0.60711  0.162444 -0.551629  0.350282
17  3.93933  0.60711  0.162444 -0.551629  0.350282
18  3.93933  0.60711  0.162444 -0.551629  0.350282
19  3.93933  0.60711  0.162444 -0.551629  0.350282
20  3.93933  0.60711  0.162444 -0.551629  0.350282
21  3.93933  0.60711  0.162444 -0.551629  0.350282
22  3.93933  0.60711  0.162444 -0.551629  0.350282
23  3.93933  0.60711  0.162444 -0.551629  0.350282
24  3.93933  0.60711  0.162444 -0.551629  0.350282
25  3.93933  0.60711  0.162444 -0.551629  0.350282
26  3.93933  0.60711  0.162444 -0.551629  0.350282
27  3.93933  0.60711  0.162444 -0.551629  0.350282
28  3.93933  0.60711  0.162444 -0.551629  0.350282
29  3.93933  0.60711  0.162444 -0.551629  0.350282
30  3.93933  0.60711  0.162444 -0.551629  0.350282

In [538]:
paraRout = pd.read_csv("/home/lin/git/summerProject/paraRout")
paraRout

k      vbar        v0       rho     sigma
0   1.490986  0.262491  0.769627 -0.634046  0.732472
1   1.472749  0.375755  0.425529 -0.629341  0.729757
2   1.473742  0.758854  0.302920 -0.690041  0.743077
3   1.531484  0.929630  0.224618 -0.600854  0.674571
4   1.552526  0.915199  0.179060 -0.417563  0.509666
5   1.561817  0.888590  0.170480 -0.270235  0.389824
6   1.612263  0.861029  0.163482 -0.152739  0.230131
7   1.760889  0.809254  0.159999 -0.073160  0.004850
8   2.122378  0.733801  0.156928 -0.073560 -0.041873
9   2.649730  0.660720  0.157081 -0.128153  0.395247
10  2.738959  0.681305  0.161223 -0.256392  0.222677
11  2.821303  0.673186  0.158193 -0.346415  0.190286
12  2.992350  0.654548  0.157582 -0.476384  0.135037
13  3.265278  0.633612  0.157838 -0.611023  0.158808
14  3.544826  0.617082  0.158987 -0.842258  0.135222
15  3.740014  0.609859  0.160937 -0.979430  0.153653
16  3.840556  0.607024  0.162432 -0.967413  0.171736
17  3.877721  0.606586  0.163347 -0.922802  0.190499
18  3.894835  0.606301  0.163640 -0.884696  0.203906
19  3.904233  0.606143  0.163723 -0.851348  0.214600
20  3.909257  0.606089  0.163739 -0.827094  0.222543
21  3.913243  0.606054  0.163710 -0.800695  0.230948
22  3.918380  0.606081  0.163631 -0.754040  0.246353
23  3.924158  0.606243  0.163496 -0.694041  0.269494
24  3.930115  0.606515  0.163288 -0.636772  0.296998
25  3.935923  0.606809  0.163016 -0.591748  0.323791
26  3.940899  0.607017  0.162730 -0.562124  0.344443
27  3.943482  0.607088  0.162515 -0.548264  0.354618
28  3.941550  0.607101  0.162447 -0.548823  0.353156
29  3.939899  0.607110  0.162442 -0.550803  0.351062
30  3.939404  0.607111  0.162443 -0.551513  0.350385

In [539]:
routs = np.abs(paraRout - newPara)/np.abs(newPara)

In [540]:
%matplotlib tk

In [541]:
plt.semilogy(routs['k'], 'rX-')
plt.semilogy(routs['vbar'], 'bX-')
plt.semilogy(routs['v0'], 'kX-')
plt.semilogy(routs['rho'], 'gX-')
plt.semilogy(routs['sigma'], 'mX-')
plt.legend([r'$|k_k - k^{\star}|/|k^{\star}|$', r'$|\overline{\upsilon}_k - \overline{\upsilon}^{\star}|/|\overline{\upsilon}^{\star}|$', r'$|(\upsilon_0)_k - \upsilon_0^{\star}|/|\upsilon_0^{\star}|$',r'$|\rho_k - \rho^{\star}|/|\rho^{\star}|$',r'$|\sigma_k - \sigma^{\star}|/|\sigma^{\star}|$',], fontsize=22)
plt.xlabel('Index of iteration k', fontsize=24)
plt.ylabel('Nomalized differences between parameters found and targets', fontsize=24)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.grid()

In [546]:
residual = np.array([ 18.5626,0.656367,0.0386427,0.00612332,0.00397574,0.00263616,0.0021414,0.00167525,0.00119962,0.00109479,0.000611794,0.000388985,0.00028076,0.000157177,6.92636e-05,2.00586e-05,5.23957e-06,3.14254e-06,3.05271e-06,3.02682e-06,2.92439e-06,2.75653e-06,2.43504e-06,2.07694e-06,1.4698e-06,6.76284e-07,1.61719e-07,1.75177e-08,2.01177e-09,1.5531e-10,3.55545e-12])

In [547]:
plt.semilogy(residual, 'bX-.')
plt.legend(['Reduction path of the objective function'], fontsize=22)
plt.xlabel('Index of iteration k', fontsize=24)
plt.ylabel('Value of the objective function', fontsize=24)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.grid()

In [552]:
realSPX = np.array([9.1488840741252240e+00,1.7091811411851889e+01,2.2648914959691634e+01,2.6899811014846122e+01,3.0485680583231822e+01,3.3640797740897938e+01,4.0647050370505333e+01,4.7099528768636183e+01,5.7288298801033175e+00,9.2961086466444964e+00,1.2681535166958508e+01,1.5766126995200002e+01,1.8532854376031942e+01,2.1014374258872692e+01,2.6925542643663544e+01,3.1741392486654934e+01,3.6957945727271277e+00,6.6622157345524320e+00,9.2549126095879259e+00,1.1605400673311641e+01,1.3743032942265044e+01,1.5710381405617595e+01,2.0885729383677450e+01,2.5059002842605203e+01,3.7707705228314581e-01,1.8536319875424612e+00,3.7214462167761813e+00,5.4514982430802350e+00,7.5101850404845027e+00,9.3132008534070359e+00,1.4313673212582712e+01,1.8479094744070874e+01,2.4809541410122794e-02,4.8386973821334811e-01,1.4651640721061439e+00,2.7313546456061153e+00,4.1237115119043048e+00,5.5585968310143228e+00,9.8995041607100340e+00,1.3720813274564101e+01])

In [553]:
realSPX.shape

(40,)

In [554]:
realVIX = np.array([6.3349628199328215e+01,6.3187554077066345e+01,6.3003396047662946e+01,6.2814838069281329e+01,6.2641277216717100e+01,6.3964437455680489e+01,6.3738105494809929e+01,6.3478651199905201e+01,6.3210519576896800e+01,6.2961530187385691e+01,6.4521373991595809e+01,6.4246055168722648e+01,6.3928225015797580e+01,6.3597344082000319e+01,6.3287945206808118e+01,6.5159862103623183e+01,6.4834143896174936e+01,6.4455224410674617e+01,6.4057533728871405e+01,6.3682788239993997e+01,6.6795373904405139e+01,6.6347261633381493e+01,6.5815955942998244e+01,6.5247066536454270e+01,6.4700717234887705e+01,6.7925725858094481e+01,6.7387484356100458e+01,6.6739908432634024e+01,6.6035775654948395e+01,6.5349603428541727e+01])

In [555]:
realVIX.shape

(30,)

In [556]:
initialSPX = np.array([1.3092411920438721e+01,2.1101603296043443e+01,2.6467840574197318e+01,3.0436603181942836e+01,3.3680609427914995e+01,3.6465683205328666e+01,4.2376506607117797e+01,4.7823462527668561e+01,1.0030945406707110e+01,1.4169739288803008e+01,1.7468915721908608e+01,2.0193086372241201e+01,2.2472088574597642e+01,2.4405409127128358e+01,2.8569320856234295e+01,3.1696381337952921e+01,7.9691137080187904e+00,1.1567174203435119e+01,1.4097118899685730e+01,1.6078117946046579e+01,1.7689246663338832e+01,1.9046836600435107e+01,2.2225645771353442e+01,2.4412906487884388e+01,2.8186743897198108e+00,5.6087245214254837e+00,7.7717411622811028e+00,9.2674609096074505e+00,1.0925142927299316e+01,1.2149875550434770e+01,1.5104408648665499e+01,1.7146673518975444e+01,9.5483848802301108e-01,2.7626710363460543e+00,4.3150507943053276e+00,5.6314781374342893e+00,6.7586607266231562e+00,7.7383266714980889e+00,1.0208904090911812e+01,1.1925184313841463e+01])

In [557]:
initialVIX = np.array([6.4261057083365259e+01,6.4098416682238508e+01,6.3913656945925169e+01,6.3724531991958742e+01,6.3550495986095491e+01,6.3799288234396833e+01,6.3572343266423751e+01,6.3312152365729780e+01,6.3043225398912199e+01,6.2793470780829075e+01,6.3317025302863762e+01,6.3041880980124517e+01,6.2724196347606643e+01,6.2393399164237849e+01,6.2084012683508490e+01,6.2691713144719046e+01,6.2366338348452324e+01,6.1987826163472938e+01,6.1590566228087852e+01,6.1216223171284675e+01,6.0666318427156412e+01,6.0218152569796374e+01,5.9686773498461626e+01,5.9117795174153578e+01,5.8571352767463502e+01,5.8794729499899049e+01,5.8256511426334228e+01,5.7608964271418579e+01,5.6904862186746421e+01,5.6218717539246526e+01])

In [558]:
optSPX = np.array([9.1488898662351641e+00,1.7091829707794112e+01,2.2648941529008528e+01,2.6899843141972852e+01,3.0485716260263825e+01,3.3640835471815123e+01,4.0647089003364464e+01,4.7099564799562685e+01,5.7288312661176271e+00,9.2961197340644617e+00,1.2681554566557002e+01,1.5766152290572940e+01,1.8532883392976437e+01,2.1014405307932254e+01,2.6925573506035022e+01,3.1741419657594083e+01,3.6957927770505457e+00,6.6622223897680426e+00,9.2549264614453151e+00,1.1605419569119290e+01,1.3743054908842224e+01,1.5710404907385643e+01,2.0885752077053930e+01,2.5059021143732526e+01,3.7707513051300490e-01,1.8536317275657865e+00,3.7214503268607770e+00,5.4515059887458515e+00,7.5101958160127635e+00,9.3132131306655790e+00,1.4313685133673840e+01,1.8479102697243672e+01,2.4809598937907837e-02,4.8387024065828782e-01,1.4651662186596668e+00,2.7313587540253037e+00,4.1237170966109158e+00,5.5586031463946277e+00,9.8995091152294936e+00,1.3720813923161211e+01])

In [559]:
optVIX = np.array([6.3349773015718817e+01,6.3187699008407726e+01,6.3003541134341440e+01,6.2814983342314811e+01,6.2641422685635618e+01,6.3964591229468788e+01,6.3738258808047568e+01,6.3478803985181244e+01,6.3210671820243121e+01,6.2961681934630242e+01,6.4521529341968474e+01,6.4246210543448711e+01,6.3928380371676440e+01,6.3597499362858322e+01,6.3288100365112726e+01,6.5160009532275680e+01,6.4834291694526939e+01,6.4455372646252385e+01,6.4057682425356518e+01,6.3682937365643433e+01,6.6795513607478469e+01,6.6347401283103210e+01,6.5816095504645020e+01,6.5247205974712443e+01,6.4700856528655194e+01,6.7925850750680084e+01,6.7387609293907047e+01,6.6740033433203678e+01,6.6035900731966194e+01,6.5349728584723110e+01])

In [573]:
diffInitialSPX = np.abs(realSPX - initialSPX)

In [574]:
diffInitialVIX = np.abs(realVIX - initialVIX)

In [600]:
diffOptSPX = np.abs(realSPX - optSPX)*100000
diffOptVIX = np.abs(realVIX - optVIX)*10000

In [576]:
VIXstrike = np.array([
    
     7.660333466800909, 7.823036262505452, 8.007866879151475,                                     
           8.197064388101637, 8.371167160297436, 7.52823178901193,                 
           7.755350918528184, 8.015741494276396, 8.284874840358377,                
           8.53482112450969, 7.430112345712659, 7.705573455122799,                 
           8.023623852982013, 8.354801898792093, 8.66454459080821,                 
           7.32872469748735, 7.654634796281677, 8.033769704753064,                 
           8.431683207193617, 8.806642128491488, 7.084911309063554,                
           7.534553012964565, 8.067681958626018, 8.638533974549638,                
           9.186775860168481, 6.910110193769552, 7.450988995253548,                
           8.10173736334907, 8.809320258894406, 9.49885695945464
])

In [577]:
VIXexp = np.array([7, 7, 7, 7, 7, 14, 14, 14, 14, 14, 21, 21, 21, 21, 21, 30, 30, 30, 30, 30, 60, 60, 60, 60, 60, 90, 90, 90, 90, 90])

In [578]:
SPXstrike = np.array([
    
    93.71, 86.03, 81.12, 77.60, 74.70, 72.16, 66.99,        
                           61.37, 99.56, 98.68, 97.28, 95.88, 94.64, 93.58,        
                           91.75, 90.25, 104.27, 104.63, 104.99, 105.30, 105.62,   
                           105.93, 106.63, 107.66, 122.87, 123.99, 124.85, 126.59, 
                           126.46, 127.15, 128.59, 130.46, 139.39, 141.02, 142.91, 
                           144.56, 146.03, 147.36, 150.05, 153.28
    
])
SPXexp = np.array([30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360])

In [593]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.dist=10
for i in range(30):
    ax.plot(np.array([VIXstrike[i], VIXstrike[i]]), np.array([VIXexp[i], VIXexp[i]]), np.array([diffInitialVIX.min()-0.0005, diffInitialVIX[i]]), 'y-.', alpha=0.5)
ax.scatter(VIXstrike, VIXexp, diffInitialVIX, s = 30, depthshade=False)
ax.set_xlabel('Strikes of VIX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of VIX options', fontsize=24, labelpad=22)
ax.set_zlabel('Errors', fontsize=24, labelpad=25)
plt.xticks(fontsize=20)
plt.yticks([7, 14, 21, 30, 60, 90], fontsize=20)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=10)
plt.grid()

In [594]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.dist=10
ax.scatter(VIXstrike, VIXexp, diffOptVIX, s = 30, depthshade=False)
for i in range(30):
    ax.plot(np.array([VIXstrike[i], VIXstrike[i]]), np.array([VIXexp[i], VIXexp[i]]), np.array([diffOptVIX.min()-0.01, diffOptVIX[i]]), 'y-.', alpha=0.5)
ax.set_xlabel('Strikes of VIX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of VIX options', fontsize=24, labelpad=22)
ax.set_zlabel(r'Errors $\times 10^4$', fontsize=24, labelpad=20)
plt.xticks(fontsize=20)
plt.yticks([7, 14, 21, 30, 60, 90], fontsize=20)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=5)
plt.grid()


In [589]:
diffOptVIX.min()

1.2489258560322014

In [599]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(SPXstrike, SPXexp, diffInitialSPX, s = 30, depthshade=False)
for i in range(40):
    ax.plot(np.array([SPXstrike[i], SPXstrike[i]]), np.array([SPXexp[i], SPXexp[i]]), np.array([diffInitialSPX.min()-0.01, diffInitialSPX[i]]), 'y-.', alpha=0.5)
ax.set_xlabel('Strikes of SPX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of SPX options', fontsize=24, labelpad=22)
ax.set_zlabel('Errors', fontsize=24, labelpad=20)
plt.xticks(fontsize=20)
plt.yticks([30, 60, 90, 120, 150, 180, 270, 360], fontsize=15)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=5)
plt.grid()

In [601]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(SPXstrike, SPXexp, diffOptSPX, s = 30, depthshade=False)
for i in range(40):
    ax.plot(np.array([SPXstrike[i], SPXstrike[i]]), np.array([SPXexp[i], SPXexp[i]]), np.array([diffOptSPX.min()-0.00000001, diffOptSPX[i]]), 'y-.', alpha=0.5)
ax.set_xlabel('Strikes of SPX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of SPX options', fontsize=24, labelpad=22)
ax.set_zlabel(r'Errors $\times 10^5$', fontsize=24, labelpad=20)
plt.xticks(fontsize=20)
plt.yticks([30, 60, 90, 120, 150, 180, 270, 360], fontsize=15)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=10)
plt.grid()