In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.special import erf
from scipy.stats import norm
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
#%matplotlib tk

In [32]:
result = pd.read_csv("/home/lin/git/summerProject/HestonCalibration_single")

In [33]:
result[['time', 'iteration', 'pv', 'jac', 'lin_sys', 'e0', 'e*', 'Je', 'Dp', 'count','count2', 'count7']].describe()

time  iteration          pv        jac     lin_sys          e0  \
count  100.000000  100.00000  100.000000  100.00000  100.000000  100.000000   
mean    14.538868  248.96000  261.750000  248.96000  260.930000   72.858040   
std      8.545839  110.34335  118.913378  110.34335  118.552146   98.979815   
min      4.360610    1.00000    9.000000    1.00000    9.000000    0.248712   
25%      8.089492  300.00000  301.000000  300.00000  300.000000    3.929137   
50%     12.339571  300.00000  304.000000  300.00000  303.000000   20.268107   
75%     20.417480  300.00000  306.000000  300.00000  305.000000  103.625479   
max     40.417339  300.00000  604.000000  300.00000  603.000000  425.821102   

                 e*           Je            Dp       count      count2  count7  
count  1.000000e+02   100.000000  1.000000e+02  100.000000  100.000000   100.0  
mean   1.012933e+00   177.529165  2.974200e-07   32.850000   32.030000     0.0  
std    5.442895e+00   740.821291  1.535559e-06   36.473146   36.808391     0.0  
min    8.175340e-07     0.000006  4.428914e-25    1.000000    0.000000     0.0  
25%    1.100467e-04     0.001370  2.917626e-18    6.000000    5.000000     0.0  
50%    4.977448e-04     0.011363  4.167211e-12   16.000000   15.000000     0.0  
75%    1.881952e-02     1.426654  7.195051e-10   52.250000   51.250000     0.0  
max    4.781055e+01  4580.483418  1.213480e-05  100.000000  100.000000     0.0

In [34]:
result[['Ok', 'Rk', 'Ovbar', 'Rvbar', 'Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma']].head(50)

Ok        Rk     Ovbar     Rvbar       Ov0       Rv0      Orho  \
0   0.839927  1.091920  0.458181  0.462785  0.270637  0.247063 -0.228219   
1   1.207720  2.650119  0.616802  0.517990  0.248016  0.185280 -0.199079   
2   0.639995  0.973332  0.339555  0.381706  0.364015  0.344505 -0.276412   
3   1.455499  3.679076  0.304626  0.285601  0.306291  0.390530 -0.709875   
4   1.827309  4.664764  0.372489  0.437401  0.672321  0.798130 -0.706097   
5   1.903876  3.079323  0.403949  0.232234  0.364908  0.926913 -0.398687   
6   2.829442  3.047822  0.429314  0.430297  0.324970  0.313739 -0.321334   
7   4.568538  4.263690  0.351590  0.349635  0.537808  0.532361 -0.868044   
8   3.093315  1.080693  0.488726  0.501668  0.530994  0.504553 -0.120800   
9   3.345727  3.021461  0.156263  0.158622  0.178822  0.173944 -0.493766   
10  2.033036  1.121009  0.312626  0.398222  0.093161  0.100521 -0.684298   
11  1.294777  0.889726  0.394433  0.426349  0.350739  0.342736 -0.473574   
12  4.102378  2.503044  0.664443  0.636842  0.860122  0.844115 -0.167391   
13  2.150322  3.848513  0.646642  0.643726  0.563948  0.506126 -0.566416   
14  0.776044  4.425715  0.977321  0.874845  0.797468  0.819080 -0.590253   
15  1.772362  3.506347  0.501833  0.533927  0.658060  0.685281 -0.489821   
16  3.378865  2.159527  0.614963  0.566898  0.739519  0.782854 -0.408350   
17  1.612140  4.394057  0.645688  0.572659  0.340855  0.199553 -0.133772   
18  0.832635  2.691661  0.936527  0.810338  0.636315  0.583870 -0.116419   
19  4.099555  2.638763  0.639420  0.835992  0.938284  0.686838 -0.221257   
20  1.973979  1.688251  0.615612  0.627144  0.667264  0.648708 -0.303819   
21  1.036279  4.619591  0.913870  0.734730  0.486942  0.311050 -0.618410   
22  1.048298  1.416655  0.007067  0.058888  0.428995  0.452222 -0.100174   
23  3.889491  1.318857  0.400293  0.388780  0.498455  0.453113 -0.104408   
24  1.694566  4.217513  0.054706  0.062238  0.087633  0.099458 -0.812982   
25  2.659645  2.123075  0.403074  0.376199  0.840540  0.807588 -0.884910   
26  1.788695  0.890432  0.636996  0.621699  0.723042  0.704518 -0.713414   
27  2.321007  1.291867  0.894973  0.924019  0.809841  0.866715 -0.431482   
28  2.881554  0.915407  0.780174  0.926581  0.495538  0.565404 -0.110831   
29  1.074940  1.822218  0.710935  0.601168  0.198164  0.154080 -0.190666   
30  4.078908  1.638160  0.732495  0.821357  0.844144  0.888563 -0.355667   
31  2.831113  4.366991  0.557962  0.527875  0.185585  0.104339 -0.712799   
32  1.811564  3.685094  0.301697  0.378186  0.741079  0.876616 -0.211070   
33  0.822752  3.266149  0.176241  0.325502  0.512934  0.608763 -0.698007   
34  2.417354  2.182804  0.128090  0.120141  0.695295  0.665213 -0.589049   
35  2.496328  4.164151  0.910773  0.899138  0.564581  0.307271 -0.223472   
36  2.189643  1.003458  0.508841  0.312064  0.555464  0.708445 -0.558201   
37  2.570078  1.919259  0.376710  0.364882  0.670968  0.627667 -0.813536   
38  1.087729  1.784600  0.449173  0.509503  0.692278  0.699017 -0.386658   
39  2.428851  1.211507  0.812287  0.790807  0.622720  0.839010 -0.854352   
40  1.002995  1.275160  0.416043  0.221863  0.026772  0.157568 -0.702634   
41  4.081992  4.980715  0.793697  0.938751  1.000046  0.361320 -0.124080   
42  1.690183  4.777818  0.652019  0.649252  0.626584  0.614425 -0.684833   
43  2.449724  4.992388  0.535889  0.553906  0.671481  0.731300 -0.249154   
44  2.834010  2.307567  0.773884  0.776853  0.844309  0.822815 -0.786614   
45  1.082270  1.530576  0.541459  0.474024  0.110112  0.089424 -0.772940   
46  2.560949  0.521185  0.699704  0.474968  0.905098  0.860274 -0.111186   
47  0.749898  3.059130  0.302748  0.380447  0.465843  0.503369 -0.133547   
48  1.048134  1.564370  0.987169  0.894469  0.435916  0.401061 -0.773651   
49  1.658611  3.539230  0.321608  0.338636  0.537432  0.710847 -0.715610   

        Rrho    Osigma    Rsigma  
0  -0.643092  0.352314  0.891224  
1  -0.766946  0.195451  0.569998  
2  -0.561421  0.256395  0.73

In [35]:
result.columns

Index(['Ik', 'Ivbar', 'Iv0', 'Irho', 'Isigma', 'Ok', 'Rk', 'Ovbar', 'Rvbar',
       'Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma', 'stopped_by', 'time',
       'iteration', 'pv', 'jac', 'lin_sys', 'e0', 'e*', 'Je', 'Dp', 'count',
       'count2', 'count7'],
      dtype='object')

In [36]:
result['stopped_by'].unique() #3, itmax, 1 small gradient, 5 increase mu

array([3, 2])

In [37]:
solved = result[result['stopped_by'] == 6]
solved.count().unique()

array([0])

In [38]:
solved.count().unique()/result.count().unique()

array([0.])

In [39]:
solved_first_time = solved[solved['count'] == 1]
solved_first_time.count().unique()

array([0])

In [40]:
DP = result[result['stopped_by'] == 2]
DP.count().unique()

array([18])

In [30]:
invalid_value = result[result['stopped_by'] == 7]
invalid_value.count().unique()

array([0])

In [31]:
DP

Ik     Ivbar       Iv0      Irho    Isigma        Ok        Rk  \
14  0.700145  0.453409  0.210009 -0.590253  0.520717  0.776044  4.425715   
16  3.382944  0.522467  0.712712 -0.408350  0.543821  3.378865  2.159527   
19  4.099555  0.639420  0.938284 -0.221257  0.793268  4.099555  2.638763   
27  2.375336  0.299641  0.225006 -0.431482  0.508726  2.321007  1.291867   
30  4.080169  0.336573  0.421829 -0.355667  0.573617  4.078908  1.638160   
35  2.164130  0.274892  0.213973 -0.223472  0.738864  2.496328  4.164151   

       Ovbar     Rvbar       Ov0   ...     pv  jac  lin_sys          e0  \
14  0.977321  0.874845  0.797468   ...     13    4       13  235.768936   
16  0.614963  0.566898  0.739519   ...     11    3       11    3.704266   
19  0.639420  0.835992  0.938284   ...      9    1        9    5.991220   
27  0.894973  0.924019  0.809841   ...     12    3       12  265.631000   
30  0.732495  0.821357  0.844144   ...     12    2       12  162.843880   
35  0.910773  0.899138  0.564581   ...    142  138      142  232.892133   

          e*           Je            Dp  count  count2  count7  
14  0.057861     7.753203  1.206535e-23    100     100       0  
16  0.019924    12.278599  2.947570e-20    100     100       0  
19  5.991220  3151.721145  3.931630e-22    100     100       0  
27  0.229598   294.080807  1.151608e-20    100     100       0  
30  4.409437  2319.498645  4.428914e-25    100     100       0  
35  0.099849     6.199046  6.385985e-20    100     100       0  

[6 rows x 28 columns]

In [173]:
invalid_value

Empty DataFrame
Columns: [Ik, Ivbar, Iv0, Irho, Isigma, Ok, Rk, Ovbar, Rvbar, Ov0, Rv0, Orho, Rrho, Osigma, Rsigma, stopped_by, time, iteration, pv, jac, lin_sys, e0, e*, Je, Dp, count, count2, count7]
Index: []

[0 rows x 28 columns]

In [174]:
itmax = result[result['stopped_by'] == 3]
itmax.count().unique()

array([86])

In [175]:
smalJac = result[result['stopped_by'] == 1]
smalJac.count().unique()

array([0])

In [176]:
solved['time'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: time, dtype: float64

In [177]:
solved_first_time['time'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: time, dtype: float64

In [178]:
solved_first_time['iteration'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: iteration, dtype: float64

In [179]:
solved['iteration'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: iteration, dtype: float64

In [180]:
solved[['Ok', 'Rk', 'Ovbar', 'Rvbar', 'Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma']].head()

Empty DataFrame
Columns: [Ok, Rk, Ovbar, Rvbar, Ov0, Rv0, Orho, Rrho, Osigma, Rsigma]
Index: []

In [181]:
#'Ik', 'Ivbar', 'Iv0', 'Irho', 'Isigma', 'Ok', 'Rk', 'Ovbar', 'Rvbar',
#'Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma', 'stopped_by', 'time',
#'iteration', 'pv', 'jac', 'lin_sys', 'e0', 'e*', 'Je', 'Dp', 'count'
   

In [182]:
disIk = np.abs(solved['Ik'] - solved['Rk']).mean()
disIk

nan

In [183]:
disIvbar = np.abs(solved['Ivbar'] - solved['Rvbar']).mean()
disIvbar

nan

In [184]:
disIv0 = np.abs(solved['Iv0'] - solved['Rv0']).mean()
disIv0

nan

In [185]:
disIsigma = np.abs(solved['Isigma'] - solved['Rsigma']).mean()
disIsigma

nan

In [42]:
disIrho = np.abs(solved['Irho'] - solved['Rrho']).mean()
disIrho

nan

In [43]:
disOk = np.abs(solved['Ok'] - solved['Rk']).mean()
disOk

nan

In [44]:
disOvbar = np.abs(solved['Ovbar'] - solved['Rvbar']).mean()
disOvbar

nan

In [45]:
disOsigma = np.abs(solved['Osigma'] - solved['Rsigma']).mean()
disOsigma

nan

In [46]:
disOrho = np.abs(solved['Orho'] - solved['Rrho']).mean()
disOrho

nan

In [47]:
disOv0 = np.abs(solved['Ov0'] - solved['Rv0']).mean()
disOv0

nan

In [168]:
solved.describe()

Ik       Ivbar         Iv0        Irho      Isigma          Ok  \
count  294.000000  294.000000  294.000000  294.000000  294.000000  294.000000   
mean     2.955595    0.502017    0.495408   -0.469857    0.516416    2.725044   
std      1.272767    0.249191    0.250954    0.239082    0.255326    1.283044   
min      0.524320    0.058888    0.050191   -0.899970    0.053500    0.503685   
25%      1.960903    0.290517    0.291041   -0.683412    0.302155    1.680550   
50%      2.993435    0.528671    0.483213   -0.428741    0.525019    2.745026   
75%      4.030931    0.705014    0.707375   -0.266339    0.736681    3.768474   
max      4.999257    0.947283    0.947124   -0.105745    0.945974    4.974093   

               Rk       Ovbar       Rvbar         Ov0     ...              pv  \
count  294.000000  294.000000  294.000000  294.000000     ...      294.000000   
mean     2.725114    0.532333    0.532331    0.483520     ...       39.802721   
std      1.283606    0.256547    0.256556    0.257248     ...       37.215384   
min      0.502703    0.050980    0.050920    0.050363     ...       11.000000   
25%      1.681296    0.320523    0.320335    0.264727     ...       21.000000   
50%      2.745030    0.555393    0.555392    0.493486     ...       30.000000   
75%      3.769379    0.749525    0.749536    0.687830     ...       42.000000   
max      4.972309    0.943857    0.943858    0.949116     ...      306.000000   

              jac     lin_sys            e0            e*            Je  \
count  294.000000  294.000000  2.940000e+02  2.940000e+02  2.940000e+02   
mean    32.833333   38.802721  1.616883e+08  5.887403e-11  1.344602e-05   
std     32.489895   37.215384  1.822791e+09  3.082245e-11  2.366731e-05   
min     10.000000   10.000000  4.772845e-04  2.554072e-13  1.129603e-07   
25%     18.000000   20.000000  5.558847e-02  2.993846e-11  3.095737e-06   
50%     23.000000   29.000000  1.619138e-01  6.523589e-11  6.439508e-06   
75%     35.750000   41.000000  6.808053e-01  8.732357e-11  1.376397e-05   
max    298.000000  305.000000  2.581340e+10  9.990906e-11  2.205851e-04   

                 Dp       count      count2      count7  
count  2.940000e+02  294.000000  294.000000  294.000000  
mean   1.313649e-05    1.612245    0.598639    0.013605  
std    4.689472e-05    2.737551    2.736830    0.116044  
min    2.075339e-10    1.000000    0.000000    0.000000  
25%    1.114510e-07    1.000000    0.000000    0.000000  
50%    7.961155e-07    1.000000    0.000000    0.000000  
75%    5.338812e-06    1.000000    0.000000    0.000000  
max    6.045803e-04   43.000000   42.000000    1.000000  

[8 rows x 28 columns]

In [169]:
solved[solved['iteration']==30]

Ik     Ivbar       Iv0      Irho    Isigma        Ok        Rk  \
179  2.123662  0.528175  0.246657 -0.405154  0.924438  1.689812  1.689313   
251  4.266063  0.905882  0.333166 -0.865991  0.923419  1.162924  1.162882   
290  3.242873  0.295908  0.746932 -0.216498  0.633355  4.234708  4.235667   

        Ovbar     Rvbar       Ov0   ...    pv  jac  lin_sys        e0  \
179  0.451003  0.450927  0.844178   ...    43   30       42  0.124764   
251  0.374584  0.374574  0.363362   ...    35   30       34  0.405930   
290  0.280341  0.280353  0.522222   ...    31   30       30  0.070847   

               e*        Je            Dp  count  count2  count7  
179  5.660375e-11  0.000005  1.100683e-07      1       0       0  
251  6.212185e-11  0.000011  1.693047e-08      1       0       0  
290  8.159173e-11  0.000004  1.058053e-07      1       0       0  

[3 rows x 28 columns]

In [170]:
example = solved[solved.index==567]
example

Empty DataFrame
Columns: [Ik, Ivbar, Iv0, Irho, Isigma, Ok, Rk, Ovbar, Rvbar, Ov0, Rv0, Orho, Rrho, Osigma, Rsigma, stopped_by, time, iteration, pv, jac, lin_sys, e0, e*, Je, Dp, count, count2, count7]
Index: []

[0 rows x 28 columns]

In [34]:
example.values

array([[ 2.00310794e+00,  7.66502906e-01,  2.78598016e-01,
        -6.06551157e-01,  2.17311675e-01,  8.19289377e-01,
         8.19279086e-01,  4.52754204e-01,  4.52758708e-01,
         6.38483161e-02,  6.38483542e-02, -7.18027819e-01,
        -7.18027981e-01,  7.22171706e-01,  7.22171617e-01,
         6.00000000e+00,  4.30497000e-01,  3.00000000e+01,
         3.30000000e+01,  3.00000000e+01,  3.20000000e+01,
         1.12281824e+07,  3.97140758e-13,  2.59803814e-06,
         1.15641984e-07,  1.00000000e+00]])

In [40]:
np.abs(example['Ik'] - example['Rk'])

567    1.183829
dtype: float64

In [41]:
np.abs(example['Ivbar'] - example['Rvbar'])

567    0.313744
dtype: float64

In [42]:
np.abs(example['Iv0'] - example['Rv0'])

567    0.21475
dtype: float64

In [43]:
np.abs(example['Isigma'] - example['Rsigma'])

567    0.50486
dtype: float64

In [44]:
np.abs(example['Irho'] - example['Rrho'])

567    0.111477
dtype: float64

In [45]:
realPara = (example[['Rk', 'Rvbar', 'Rv0','Rrho', 'Rsigma']])
realPara.columns = ['k', 'vbar', 'v0', 'rho', 'sigma']
realPara.reset_index(drop=True, inplace=True)
newPara = pd.DataFrame(index=range(31), columns=realPara.columns)
for i in range(31):
    for name in realPara.columns:
        newPara.iloc[i][name] = realPara.iloc[0][name]
newPara

k      vbar         v0       rho     sigma
0   0.819279  0.452759  0.0638484 -0.718028  0.722172
1   0.819279  0.452759  0.0638484 -0.718028  0.722172
2   0.819279  0.452759  0.0638484 -0.718028  0.722172
3   0.819279  0.452759  0.0638484 -0.718028  0.722172
4   0.819279  0.452759  0.0638484 -0.718028  0.722172
5   0.819279  0.452759  0.0638484 -0.718028  0.722172
6   0.819279  0.452759  0.0638484 -0.718028  0.722172
7   0.819279  0.452759  0.0638484 -0.718028  0.722172
8   0.819279  0.452759  0.0638484 -0.718028  0.722172
9   0.819279  0.452759  0.0638484 -0.718028  0.722172
10  0.819279  0.452759  0.0638484 -0.718028  0.722172
11  0.819279  0.452759  0.0638484 -0.718028  0.722172
12  0.819279  0.452759  0.0638484 -0.718028  0.722172
13  0.819279  0.452759  0.0638484 -0.718028  0.722172
14  0.819279  0.452759  0.0638484 -0.718028  0.722172
15  0.819279  0.452759  0.0638484 -0.718028  0.722172
16  0.819279  0.452759  0.0638484 -0.718028  0.722172
17  0.819279  0.452759  0.0638484 -0.718028  0.722172
18  0.819279  0.452759  0.0638484 -0.718028  0.722172
19  0.819279  0.452759  0.0638484 -0.718028  0.722172
20  0.819279  0.452759  0.0638484 -0.718028  0.722172
21  0.819279  0.452759  0.0638484 -0.718028  0.722172
22  0.819279  0.452759  0.0638484 -0.718028  0.722172
23  0.819279  0.452759  0.0638484 -0.718028  0.722172
24  0.819279  0.452759  0.0638484 -0.718028  0.722172
25  0.819279  0.452759  0.0638484 -0.718028  0.722172
26  0.819279  0.452759  0.0638484 -0.718028  0.722172
27  0.819279  0.452759  0.0638484 -0.718028  0.722172
28  0.819279  0.452759  0.0638484 -0.718028  0.722172
29  0.819279  0.452759  0.0638484 -0.718028  0.722172
30  0.819279  0.452759  0.0638484 -0.718028  0.722172

In [47]:
paraRout = pd.read_csv("/home/lin/git/summerProject/paraRout")
paraRout

k      vbar        v0       rho     sigma
0   2.003108  0.766503  0.278598 -0.606551  0.217312
1   1.994029  0.724699  0.189030 -0.610187  0.228518
2   1.982846  0.677274  0.140961 -0.611728  0.235546
3   1.970775  0.626121  0.111046 -0.611977  0.241220
4   1.958803  0.573471  0.089061 -0.611404  0.246896
5   1.948925  0.527419  0.067376 -0.610923  0.253178
6   1.944743  0.506576  0.042040 -0.612459  0.258198
7   1.941752  0.490938  0.022661 -0.613929  0.261750
8   1.938261  0.471839  0.007217 -0.614936  0.265345
9   1.934198  0.448370 -0.009117 -0.616059  0.269575
10  1.930017  0.422237 -0.025356 -0.617622  0.274013
11  1.925383  0.390267 -0.033610 -0.619679  0.279294
12  1.919578  0.345077 -0.025009 -0.623126  0.287150
13  1.914692  0.294875 -0.007045 -0.624905  0.292908
14  1.906295  0.215047  0.037228 -0.632205  0.309901
15  1.900410  0.180697  0.053501 -0.630926  0.337019
16  1.898877  0.188379  0.050549 -0.615934  0.361106
17  1.893367  0.196327  0.050899 -0.608160  0.424227
18  1.878629  0.214886  0.053882 -0.642145  0.545086
19  1.844444  0.245552  0.059049 -0.699240  0.696172
20  1.768882  0.272215  0.062338 -0.719810  0.788244
21  1.598893  0.291626  0.063138 -0.722865  0.790735
22  1.376840  0.317133  0.063442 -0.722299  0.773212
23  1.149316  0.353749  0.063754 -0.721801  0.756365
24  1.005975  0.389744  0.063915 -0.721154  0.745035
25  0.879581  0.426635  0.063927 -0.719500  0.730871
26  0.817866  0.452653  0.063948 -0.718808  0.724791
27  0.814098  0.454967  0.063864 -0.718079  0.722034
28  0.819401  0.452681  0.063847 -0.718019  0.722150
29  0.818976  0.452886  0.063849 -0.718030  0.722160
30  0.819289  0.452755  0.063848 -0.718028  0.722172

In [48]:
routs = np.abs(paraRout - newPara)/np.abs(newPara)

In [49]:
%matplotlib tk

In [50]:
plt.semilogy(routs['k'], 'rX-')
plt.semilogy(routs['vbar'], 'bX-')
plt.semilogy(routs['v0'], 'kX-')
plt.semilogy(routs['rho'], 'gX-')
plt.semilogy(routs['sigma'], 'mX-')
plt.legend([r'$|k_k - k^{\star}|/|k^{\star}|$', r'$|\overline{\upsilon}_k - \overline{\upsilon}^{\star}|/|\overline{\upsilon}^{\star}|$', r'$|(\upsilon_0)_k - \upsilon_0^{\star}|/|\upsilon_0^{\star}|$',r'$|\rho_k - \rho^{\star}|/|\rho^{\star}|$',r'$|\sigma_k - \sigma^{\star}|/|\sigma^{\star}|$',], fontsize=22)
plt.xlabel('Index of iteration k', fontsize=24)
plt.ylabel('Nomalized differences between parameters found and targets', fontsize=24)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.grid()

In [54]:
residual = np.array([11228182.46038808,807255.2860647117,76039.65750674544,10062.25865084798,1887.359525438133,351.3059154344626,49.09839337737781,10.14481475124527,3.317012356056412,1.152402586648755,0.4177379994440593,0.2055414882174497,0.1282323013866701,0.08938729119401917,0.03267351837427038,0.02753496116476249,0.02170500399809178,0.01789866338104146,0.0108093724732074,0.004463637920357317,0.001246749982923448,0.000733681009537488,0.0005813803495587621,0.0005499026977308425,0.0001869581706586826,0.0001337921316549374,1.328981933037579e-05,6.953217715155133e-08,1.436982211690292e-09,2.082707307407935e-10,3.971677980382377e-13])

In [55]:
plt.semilogy(residual, 'bX-.')
plt.legend(['Reduction path of the objective function'], fontsize=22)
plt.xlabel('Index of iteration k', fontsize=24)
plt.ylabel('Value of the objective function', fontsize=24)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.grid()

In [56]:
realSPX = np.array([0.07478998780360964,0.1511881858006229,0.2027213809295823,0.2410147787627178,0.2731537190898699,0.3015950796032961,0.3634066696340293,0.4259388798643055,0.03423046264597641,0.05564391048588092,0.07821984090287659,0.099843150859326,0.1197462338377685,0.1379057817951416,0.1810112295762004,0.2187702577360547,0.01335175190303648,0.02636982030737595,0.03824713876862126,0.0496783014582497,0.06059723482555364,0.07117410881843453,0.1020129531561916,0.1289858583611486,5.507656245541976e-06,0.0003417334933978206,0.001793873971183487,0.004031474194149178,0.008600842548238147,0.01362447696797399,0.03324075369386573,0.05432814885255527,-3.810543297612796e-08,2.314515999204069e-06,4.939701354645699e-05,0.0002662664419762034,0.0008058353744827404,0.001794209495300502,0.008420466884001467,0.01913449284155004])

In [57]:
realSPX.shape

(40,)

In [58]:
realVIX = np.array([0.4361447852517755,0.4361285192330442,0.4361100410116878,0.4360911262154472,0.4360737204975733,0.4401700049222158,0.4401473105482878,0.4401212915991083,0.4400943990480715,0.4400694237215474,0.444095252384773,0.444067741566241,0.4440359772754752,0.4440029019018689,0.4439719673173388,0.448990974997294,0.4489584442123633,0.4489206007818745,0.4488808829620785,0.4488434563586114,0.4641372127842907,0.4640924073448026,0.4640392826533965,0.4639823989716804,0.4639277683211129,0.4776670574651534,0.4776132479141628,0.4775485079437879,0.4774781137667365,0.4774095149226167])

In [59]:
realVIX.shape

(30,)

In [64]:
initialSPX = np.array([0.09992093840981257,0.1781617982807032,0.2329235066714602,0.2749930226235151,0.3106782873547143,0.3422820828275765,0.4136692872971223,0.4799118705242865,0.06709033572913849,0.1030770804774587,0.1363788848334239,0.1667389423064116,0.1942112806390227,0.2191460100470349,0.2801283189375107,0.3313237149002883,0.04678646016073475,0.07706737451786527,0.1026386167084481,0.1257976614788078,0.1470885834874019,0.1669809914495011,0.2208814395382606,0.2660901298496009,0.00805724474535678,0.02619998314958867,0.04594411507825658,0.06353266005681651,0.0845012973891318,0.1029888528928549,0.1555681389458044,0.2010274887932842,0.00113129600711326,0.008799144330690551,0.02058895127311239,0.0343790256400592,0.04911691405801335,0.06425633203050402,0.1107907741822713,0.1531136597025941])

In [65]:
initialVIX = np.array([0.7497088142563657,0.7496925794246937,0.7496741366318193,0.7496552581010384,0.749637885755193,0.7544871438544895,0.7544644584834362,0.7544384498561026,0.754411567973601,0.7543866025551501,0.7590845992667851,0.759057078822633,0.7590253034180673,0.7589922164719897,0.7589612710640637,0.7646273075502549,0.7645947675448533,0.764556913388064,0.7645171843106657,0.7644797470989914,0.7807823437948596,0.7807375271756094,0.7806843892287504,0.7806274913537966,0.7805728470723017,0.7939488285269251,0.7938950067276593,0.7938302520211628,0.7937598418211995,0.7936912273630572])

In [60]:
optSPX = np.array([0.07478998330825991,0.1511881809624669,0.2027213742904438,0.2410147693292858,0.2731537060320192,0.3015950621576541,0.3634066339837972,0.4259388229055147,0.03423045697801266,0.05564390453620619,0.07821983386961903,0.09984314121849809,0.1197462200079833,0.1379057622601254,0.1810111849754902,0.2187701777850605,0.01335174762510088,0.0263698169715359,0.03824713629624694,0.0496782984407956,0.06059722951085358,0.07117409936709045,0.1020129208234652,0.1289857908825274,5.507653235168098e-06,0.0003417335484702847,0.001793874618338194,0.004031475693787042,0.008600844949581476,0.01362447892781697,0.03324074348211809,0.05432811081199039,-3.810543297612796e-08,2.314515445320785e-06,4.939699886146426e-05,0.0002662663642584691,0.0008058351466696318,0.001794208949200881,0.00842046207863016,0.01913447334959481])

In [61]:
optVIX = np.array([0.4361444591264983,0.4361281931076638,0.4361097148861902,0.4360908000898298,0.4360733943718457,0.4401696681720964,0.4401469737981951,0.4401209548490461,0.4400940622980407,0.440069086971546,0.4440949049733128,0.4440673941548383,0.4440356298641388,0.4440025544906016,0.4439716199061359,0.4489906132256151,0.4489580824407348,0.4489202390103048,0.4488805211905705,0.4488430945871615,0.4641367984359148,0.4640919929964292,0.464038868305026,0.4639819846233131,0.4639273539727485,0.4776665850977025,0.4776127755466941,0.477548035576298,0.4774776413992233,0.4774090425550807])

In [66]:
diffInitialSPX = np.abs(realSPX - initialSPX)

In [67]:
diffInitialVIX = np.abs(realVIX - initialVIX)

In [68]:
diffOptSPX = np.abs(realSPX - optSPX)
diffOptVIX = np.abs(realVIX - optVIX)

In [69]:
VIXstrike = np.array([0.07660333466800909, 0.07823036262505452, 0.08007866879151475,
                      0.08197064388101638, 0.08371167160297435, 0.07528231789011931,
                      0.07755350918528185, 0.08015741494276396, 0.08284874840358378,
                      0.0853482112450969,  0.07430112345712658, 0.077055734551228,
                      0.08023623852982013, 0.08354801898792094, 0.08664544590808211,
                      0.0732872469748735,  0.07654634796281677, 0.08033769704753065,
                      0.08431683207193616, 0.08806642128491488, 0.07084911309063555,
                      0.07534553012964565, 0.08067681958626018, 0.08638533974549638,
                      0.0918677586016848,  0.06910110193769552, 0.07450988995253548,
                      0.08101737363349071, 0.08809320258894406, 0.0949885695945464])

In [70]:
VIXexp = np.array([7, 7, 7, 7, 7, 14, 14, 14, 14, 14, 21, 21, 21, 21, 21, 30, 30, 30, 30, 30, 60, 60, 60, 60, 60, 90, 90, 90, 90, 90])

In [71]:
SPXstrike = np.array([0.9371, 0.8603, 0.8112, 0.7760, 0.7470, 0.7216, 0.6699,
                      0.6137, 0.9956, 0.9868, 0.9728, 0.9588, 0.9464, 0.9358,
                      0.9175, 0.9025, 1.0427, 1.0463, 1.0499, 1.0530, 1.0562,
                      1.0593, 1.0663, 1.0766, 1.2287, 1.2399, 1.2485, 1.2659,
                      1.2646, 1.2715, 1.2859, 1.3046, 1.3939, 1.4102, 1.4291,
                      1.4456, 1.4603, 1.4736, 1.5005, 1.5328])
SPXexp = np.array([30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360,
                   30, 60, 90, 120, 150, 180, 270, 360])

In [77]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.dist=10
for i in range(30):
    ax.plot(np.array([VIXstrike[i], VIXstrike[i]]), np.array([VIXexp[i], VIXexp[i]]), np.array([diffInitialVIX.min()-0.0005, diffInitialVIX[i]]), 'y-.', alpha=0.5)
ax.scatter(VIXstrike, VIXexp, diffInitialVIX, s = 30, depthshade=False)
ax.set_xlabel('Strikes of VIX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of VIX options', fontsize=24, labelpad=22)
ax.set_zlabel('Errors', fontsize=24, labelpad=45)
plt.xticks(fontsize=20)
plt.yticks([7, 14, 21, 30, 60, 90], fontsize=20)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=20)
plt.grid()

In [80]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.dist=10
ax.scatter(VIXstrike, VIXexp, diffOptVIX, s = 30, depthshade=False)
for i in range(30):
    ax.plot(np.array([VIXstrike[i], VIXstrike[i]]), np.array([VIXexp[i], VIXexp[i]]), np.array([diffOptVIX.min()-0.00000001, diffOptVIX[i]]), 'y-.', alpha=0.5)
ax.set_xlabel('Strikes of VIX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of VIX options', fontsize=24, labelpad=22)
ax.set_zlabel('Errors', fontsize=24, labelpad=20)
plt.xticks(fontsize=20)
plt.yticks([7, 14, 21, 30, 60, 90], fontsize=20)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=5)
plt.grid()


In [85]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(SPXstrike, SPXexp, diffInitialSPX, s = 30, depthshade=False)
for i in range(40):
    ax.plot(np.array([SPXstrike[i], SPXstrike[i]]), np.array([SPXexp[i], SPXexp[i]]), np.array([diffInitialSPX.min()-0.01, diffInitialSPX[i]]), 'y-.', alpha=0.5)
ax.set_xlabel('Strikes of SPX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of SPX options', fontsize=24, labelpad=22)
ax.set_zlabel('Errors', fontsize=24, labelpad=40)
plt.xticks(fontsize=20)
plt.yticks([30, 60, 90, 120, 150, 180, 270, 360], fontsize=15)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=20)
plt.grid()

In [84]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(SPXstrike, SPXexp, diffOptSPX, s = 30, depthshade=False)
for i in range(40):
    ax.plot(np.array([SPXstrike[i], SPXstrike[i]]), np.array([SPXexp[i], SPXexp[i]]), np.array([diffOptSPX.min()-0.00000001, diffOptSPX[i]]), 'y-.', alpha=0.5)
ax.set_xlabel('Strikes of SPX options', fontsize=24, labelpad=22)
ax.set_ylabel('Maturities of SPX options', fontsize=24, labelpad=22)
ax.set_zlabel('Errors', fontsize=24, labelpad=20)
plt.xticks(fontsize=20)
plt.yticks([30, 60, 90, 120, 150, 180, 270, 360], fontsize=15)
for t in ax.zaxis.get_major_ticks(): t.label.set_fontsize(20)
ax.tick_params(axis='z', which='major', pad=10)
plt.grid()