In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.special import erf
from scipy.stats import norm
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
#%matplotlib tk

In [2]:
result = pd.read_csv("/home/lin/git/summerProject/Heston++onSPXonly_num_100run")

In [3]:
result[['time', 'iteration', 'pv', 'jac', 'lin_sys', 'e0', 'e*', 'Je', 'Dp', 'count','count2', 'count7']].describe()

time     iteration            pv          jac       lin_sys  \
count  100.000000    100.000000    100.000000   100.000000    100.000000   
mean     5.388109    761.540000   1790.200000    73.400000    761.600000   
std     20.795142   3094.377271   7054.962857   282.927017   3094.404585   
min      0.183818     22.000000     65.000000     3.000000     22.000000   
25%      0.662529     84.500000    211.500000     9.000000     84.500000   
50%      1.487893    206.500000    501.500000    21.000000    206.500000   
75%      3.067744    424.000000   1058.500000    45.250000    424.000000   
max    200.537157  30000.000000  68193.000000  2728.000000  30000.000000   

                 e0            e*            Je          Dp       count  \
count  1.000000e+02  1.000000e+02  1.000000e+02  100.000000  100.000000   
mean   2.101206e+05  3.307588e+04  1.040762e+05    0.000083    1.390000   
std    1.351410e+06  3.307588e+05  1.040762e+06    0.000265    0.983654   
min    9.874506e-04  1.110573e-11  4.597017e-17    0.000000    1.000000   
25%    4.302101e-02  8.661107e-11  1.105764e-05    0.000005    1.000000   
50%    1.427714e-01  9.687205e-11  4.959657e-05    0.000023    1.000000   
75%    2.646230e-01  9.969137e-11  1.653122e-04    0.000086    1.000000   
max    1.083170e+07  3.307588e+06  1.040762e+07    0.002553    7.000000   

       count2      count7  
count   100.0  100.000000  
mean      0.0    0.390000  
std       0.0    0.983654  
min       0.0    0.000000  
25%       0.0    0.000000  
50%       0.0    0.000000  
75%       0.0    0.000000  
max       0.0    6.000000

In [4]:
result['stopped_by'].unique()
#This show the reasons for stopping:
#1 - stopped by small gradient J^T e
#2 - stopped by small Dp
#3 - stopped by itmax
#4 - singular matrix. Restart from current p with increased \mu
#5 - no further error reduction is possible. Restart with increased mu
#6 - stopped by small ||e||_2
#7 - stopped by invalid (i.e. NaN or Inf) "func" values; a user error

array([6, 5, 1, 3])

In [5]:
#number of solved cases, allowing restart when stopped by 7 or 2
solved = result[result['stopped_by'] == 6]
solved.count().unique()

array([82])

In [6]:
#percentage of solved
solved.count().unique()/result.count().unique()

array([0.82])

In [7]:
#number of solved cases at the first try
solved_first_time = solved[solved['count'] == 1]
solved_first_time.count().unique()

array([70])

In [8]:
#number of cases stopped by small Dp (update of parameter)
DP = result[result['stopped_by'] == 2]
DP.count().unique()

array([0])

In [9]:
#number of cases that stopped by max iteration
itmax = result[result['stopped_by'] == 3]
itmax.count().unique()

array([1])

In [10]:
#number of cases that stopped by mall gradient J^T e
smalJac = result[result['stopped_by'] == 1]
smalJac.count().unique()

array([11])

In [11]:
#average time for all solved cases
solved['time'].describe()['mean']

2.617482292682926

In [12]:
#average time for cases solved without restart
solved_first_time['time'].describe()['mean']

2.6015538142857144

In [13]:
#Average number of iteration for solved cases
solved_first_time['iteration'].describe()['mean']

358.3285714285714

In [14]:
#Average number of iteration for all solved cases
solved['iteration'].describe()['mean']

359.7926829268293

In [15]:
#All solved cases
solved[['Ok', 'Rk', 'Ovbar', 'Rvbar','Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma', 'OI1', 'RI1', 'OI2', 'RI2', 'stopped_by', 'e*']]

Ok        Rk     Ovbar     Rvbar       Ov0       Rv0      Orho  \
0   1.101482  1.091920  0.460508  0.462785  0.247157  0.247063 -0.642976   
2   4.237238  4.539453  0.067278  0.104508  0.507463  0.504071 -0.355506   
3   2.421126  3.332945  0.339976  0.702871  0.584745  0.849715 -0.444153   
4   2.848193  4.508319  1.311450  0.807836  0.356114  0.241476 -0.174441   
7   2.748393  4.444546  0.537655  0.706773  0.933380  0.694078 -0.781358   
8   3.795721  2.815968  0.272563  0.445753  0.293362  0.775985 -0.448639   
9   1.259379  1.460961  0.341566  0.399941  1.044059  0.902791 -0.291474   
10  0.965031  0.957368  0.615777  0.621246  0.695765  0.765293 -0.771128   
11  1.059134  1.922033  0.137438  0.525693  0.560368  0.579307 -0.465136   
13  2.624883  2.173594  0.326741  0.329152  0.143679  0.143418 -0.705015   
14  1.003625  0.507458  0.341029  0.076420  0.277020  0.490687 -1.778141   
15  3.870150  3.593365  0.612444  0.802586  0.617001  0.926012 -0.200879   
16  1.126083  1.246674  0.124871  0.193782  0.596730  0.645794 -0.956114   
17  3.379552  4.728764  0.510002  0.279462  0.313528  0.161464 -0.166322   
19  3.341367  3.207369  0.507745  0.517403  0.193209  0.195277 -0.561625   
20  3.931867  4.195298  0.191957  0.257243  0.883944  0.859569 -0.611066   
21  2.661713  3.079323  0.041115  0.232234  0.967325  0.926913 -0.484322   
22  0.676719  0.641317  0.510392  0.519993  0.299764  0.299478 -0.569041   
23  3.384536  0.830799  0.584331  0.485486  0.318283  0.499692 -1.771303   
24  1.957413  1.169543  0.615483  0.945861  0.267139  0.412466 -1.464547   
25  4.541209  4.643733  0.517604  0.514878  0.290373  0.287720 -0.762487   
26  1.358300  0.832326  0.586122  0.559564  0.396034  0.430297 -0.346142   
28  4.344580  2.911804  0.735495  0.886901  0.232388  0.268906 -0.613717   
29  4.745019  3.609192  0.678817  0.562406  0.483894  0.441053 -0.243968   
30  2.954984  2.772765  0.200629  0.156558  0.648243  0.652014 -0.409517   
31  3.334896  3.521082  0.864933  0.847859  0.363705  0.357663 -0.654538   
32  4.050830  4.067511  0.243063  0.242524  0.399831  0.392565 -0.826370   
33  2.895343  2.270529  0.591128  0.798396  0.132500  0.166648 -1.161276   
34  1.928048  1.915734  0.167519  0.163330  0.170346  0.169964 -0.200369   
35  2.804132  2.941701  0.870243  0.847940  0.382116  0.376334 -0.337292   
..       ...       ...       ...       ...       ...       ...       ...   
64  0.964033  0.823916  0.230705  0.217290  0.273922  0.264072 -0.249344   
65  3.465916  4.077565  0.294297  0.326773  0.314275  0.340616 -0.154159   
66  3.057239  2.821061  0.619237  0.586958  0.706975  0.718827 -0.378667   
67  3.401140  3.144413  0.735936  0.945800  0.085694  0.108169 -0.453201   
68  1.046890  1.053814  0.155389  0.158405  0.164946  0.170682 -0.445589   
69  3.414151  4.100145  0.468438  0.578080  0.874389  0.780661 -0.482318   
70  3.593866  1.760504  0.250175  0.250870  0.196795  0.507324 -0.656062   
71  4.322158  4.359630  0.382395  0.381762  0.231276  0.230978 -0.651487   
73  1.788358  3.307682 -0.125612  0.475873  0.864683  0.742806 -0.298973   
74  0.675649  0.611464  0.447094  0.469716  0.430972  0.422764 -0.268038   
75  2.923995  2.764298  0.464551  0.491245  0.279028  0.298147 -0.836997   
76  1.129595  1.255678  0.680006  0.719452  0.661103  0.653023 -0.686917   
77  1.510913  0.817658  0.614079  0.050006  0.669717  0.925230 -0.749650   
78  2.129819  2.091340  0.171894  0.170201  0.260141  0.248575 -0.204736   
79  1.491888  1.158994  0.655270  0.518800  0.665554  0.826693 -1.191824   
80  4.339559  4.624223  0.956019  0.819080  0.197388  0.172608 -0.202148   
81  3.209745  2.968168  0.146109  0.073320  0.725995  0.737194 -0.490484   
82  2.752086  1.418416  0.751903  0.109466  0.769594  0.933052 -0.578806   
83  4.616378  4.633710  0.081267  0.081507  0.203288  0.204986 -0.328885   
85  3.352167  3.247339  0.778067  0.795041  0.067066  0.067663 -0.812344   
86  3.228316  2.438392  0.535311  0.465290  0.514650  0.61

In [16]:
#next 7 blocks show the average distance between initial guess and real parameter
disIk = np.abs(solved['Ik'] - solved['Rk']).mean()
disIk

1.3127838853444715

In [17]:
disIvbar = np.abs(solved['Ivbar'] - solved['Rvbar']).mean()
disIvbar

0.254162999068965

In [18]:
disIv0 = np.abs(solved['Iv0'] - solved['Rv0']).mean()
disIv0

0.26678791367097665

In [19]:
disIsigma = np.abs(solved['Isigma'] - solved['Rsigma']).mean()
disIsigma

0.2843712988409799

In [20]:
disIrho = np.abs(solved['Irho'] - solved['Rrho']).mean()
disIrho

0.22712977540061483

In [21]:
disII1 = np.abs(solved['II1'] - solved['RI1']).mean()
disII1

0.0003184227905100554

In [22]:
disII2 = np.abs(solved['II2'] - solved['RI2']).mean()
disII2

0.0002872592169731074

In [23]:
#next 7 blocks show the average distance between optimal found and real parameter
disOk = np.abs(solved['Ok'] - solved['Rk']).mean()
disOk

0.5330455100751733

In [24]:
disOvbar = np.abs(solved['Ovbar'] - solved['Rvbar']).mean()
disOvbar

0.12365936004381864

In [25]:
disOsigma = np.abs(solved['Osigma'] - solved['Rsigma']).mean()
disOsigma

0.02777336872357968

In [26]:
disOrho = np.abs(solved['Orho'] - solved['Rrho']).mean()
disOrho

0.09216262964701982

In [27]:
disOv0 = np.abs(solved['Ov0'] - solved['Rv0']).mean()
disOv0

0.09062995305593567

In [28]:
disOI1 = np.abs(solved['OI1'] - solved['RI1']).mean()
disOI1

0.003455402948824419

In [29]:
disOI2 = np.abs(solved['OI2'] - solved['RI2']).mean()
disOI2

0.003041995834065906