In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.special import erf
from scipy.stats import norm
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
#%matplotlib tk

In [2]:
result = pd.read_csv("/home/lin/git/summerProject/Heston++onSPXonly_ana_estar15_100run")

In [3]:
result[['time', 'iteration', 'pv', 'jac', 'lin_sys', 'e0', 'e*', 'Je', 'Dp', 'count','count2', 'count7']].describe()

time   iteration          pv         jac     lin_sys  \
count  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     2.620456  277.520000  305.440000  277.600000  304.440000   
std      1.710542  173.105239  201.611504  173.047375  201.611504   
min      0.406752   44.000000   45.000000   44.000000   44.000000   
25%      1.079037  114.750000  129.750000  114.750000  128.750000   
50%      1.978325  228.500000  238.000000  228.500000  237.000000   
75%      4.394372  500.000000  501.000000  500.000000  500.000000   
max      6.087996  500.000000  704.000000  500.000000  703.000000   

                 e0            e*            Je            Dp       count  \
count  1.000000e+02  1.000000e+02  1.000000e+02  1.000000e+02  100.000000   
mean   2.517316e+05  1.316055e+04  1.993225e+05  2.401137e-06    1.330000   
std    1.472470e+06  9.382441e+04  1.512421e+06  1.566389e-05    0.841535   
min    9.874506e-04  4.667708e-19  1.520071e-12  0.000000e+00    1.000000   
25%    3.921170e-02  3.492491e-16  2.918677e-07  9.356099e-09    1.000000   
50%    1.339994e-01  9.353200e-16  8.190531e-07  3.423440e-07    1.000000   
75%    2.748652e-01  8.671862e-13  6.451634e-06  7.656390e-07    1.000000   
max    1.211478e+07  8.413986e+05  1.423435e+07  1.559902e-04    6.000000   

       count2      count7  
count   100.0  100.000000  
mean      0.0    0.330000  
std       0.0    0.841535  
min       0.0    0.000000  
25%       0.0    0.000000  
50%       0.0    0.000000  
75%       0.0    0.000000  
max       0.0    5.000000

In [4]:
result['stopped_by'].unique()
#This show the reasons for stopping:
#1 - stopped by small gradient J^T e
#2 - stopped by small Dp
#3 - stopped by itmax
#4 - singular matrix. Restart from current p with increased \mu
#5 - no further error reduction is possible. Restart with increased mu
#6 - stopped by small ||e||_2
#7 - stopped by invalid (i.e. NaN or Inf) "func" values; a user error

array([6, 3, 1, 5])

In [5]:
#number of solved cases, allowing restart when stopped by 7 or 2
solved = result[result['stopped_by'] == 6]
solved.count().unique()

array([61])

In [6]:
#percentage of solved
solved.count().unique()/result.count().unique()

array([0.61])

In [7]:
#number of solved cases at the first try
solved_first_time = solved[solved['count'] == 1]
solved_first_time.count().unique()

array([50])

In [8]:
#number of cases stopped by small Dp (update of parameter)
DP = result[result['stopped_by'] == 2]
DP.count().unique()

array([0])

In [9]:
#number of cases that stopped by max iteration
itmax = result[result['stopped_by'] == 3]
itmax.count().unique()

array([28])

In [10]:
#number of cases that stopped by mall gradient J^T e
smalJac = result[result['stopped_by'] == 1]
smalJac.count().unique()

array([8])

In [11]:
#average time for all solved cases
solved['time'].describe()['mean']

1.7985538032786885

In [12]:
#average time for cases solved without restart
solved_first_time['time'].describe()['mean']

1.7630635

In [13]:
#Average number of iteration for solved cases
solved_first_time['iteration'].describe()['mean']

193.28

In [14]:
#Average number of iteration for all solved cases
solved['iteration'].describe()['mean']

198.0327868852459

In [15]:
#All solved cases
solved[['Ok', 'Rk', 'Ovbar', 'Rvbar','Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma', 'OI1', 'RI1', 'OI2', 'RI2', 'stopped_by', 'e*']]

Ok        Rk     Ovbar     Rvbar       Ov0       Rv0      Orho  \
0   1.091935  1.091920  0.462782  0.462785  0.247063  0.247063 -0.643092   
2   2.228506  2.228640  0.872144  0.872436  0.467802  0.468001 -0.140097   
3   4.514202  4.508319  0.805474  0.807836  0.240793  0.241476 -0.204607   
7   1.450034  1.460961  0.392033  0.399941  0.906963  0.902791 -0.314628   
8   0.958333  0.957368  0.621978  0.621246  0.765146  0.765293 -0.702454   
9   1.919512  1.922033  0.525241  0.525693  0.579613  0.579307 -0.444557   
11  2.177440  2.173594  0.328619  0.329152  0.143186  0.143418 -0.721732   
13  3.594618  3.593365  0.801914  0.802586  0.924771  0.926012 -0.164391   
14  1.247102  1.246674  0.194122  0.193782  0.645663  0.645794 -0.859521   
17  3.136803  3.137071  0.073694  0.073706  0.735943  0.736109 -0.161878   
19  3.694962  3.697025  0.298984  0.298982  0.302247  0.302093 -0.524230   
20  3.078781  3.079323  0.232028  0.232234  0.926965  0.926913 -0.493460   
21  0.641366  0.641317  0.519979  0.519993  0.299479  0.299478 -0.569489   
24  4.643697  4.643733  0.514879  0.514878  0.287721  0.287720 -0.766917   
25  0.833457  0.832326  0.559738  0.559564  0.430244  0.430297 -0.334449   
26  0.585195  0.585122  0.225284  0.225211  0.520763  0.520765 -0.675837   
27  2.916204  2.911804  0.885766  0.886901  0.268625  0.268906 -0.577749   
28  3.613662  3.609192  0.561629  0.562406  0.440141  0.441053 -0.262794   
29  2.773150  2.772765  0.156657  0.156558  0.652007  0.652014 -0.409366   
30  3.520951  3.521082  0.847871  0.847859  0.357667  0.357663 -0.659708   
31  4.067451  4.067511  0.242521  0.242524  0.392569  0.392565 -0.842814   
33  1.915738  1.915734  0.163331  0.163330  0.169964  0.169964  0.200825   
34  3.196296  3.196373  0.098354  0.098354  0.780998  0.781075 -0.125477   
35  3.308010  3.308023  0.629952  0.629951  0.073400  0.073400 -0.266200   
36  2.518779  2.519241  0.674548  0.674533  0.471430  0.471388 -0.421226   
39  2.145327  2.145397  0.127932  0.127945  0.426348  0.426349 -0.360211   
40  4.322186  4.308464  0.639714  0.647911  0.908932  0.925874 -0.229691   
41  1.258165  1.258172  0.878844  0.878842  0.053437  0.053437  0.242522   
44  4.934393  4.934440  0.350213  0.350213  0.368895  0.368894 -0.357720   
47  1.270910  1.270522  0.304883  0.304545  0.869739  0.869768 -0.419451   
..       ...       ...       ...       ...       ...       ...       ...   
50  2.719455  2.719646  0.244603  0.244621  0.367831  0.367814 -0.813682   
51  4.057421  4.060203  0.275414  0.275671  0.545215  0.544832 -0.512010   
53  2.784675  2.778755  0.797988  0.801560  0.918837  0.925791 -0.219811   
54  4.730421  4.751647  0.907018  0.901367  0.392315  0.389461 -0.757662   
55  4.845048  4.846265  0.425048  0.425155  0.702598  0.702467 -0.432040   
56  1.429196  1.413338  0.709898  0.709339  0.895293  0.912393 -0.704937   
58  3.763810  3.763811  0.261794  0.261794  0.263972  0.263972 -0.757840   
60  2.795792  2.798715  0.477133  0.477298  0.577295  0.576664 -0.679871   
64  1.923352  1.922801  0.144038  0.143688  0.845383  0.845430 -0.592918   
65  0.824046  0.823916  0.217301  0.217290  0.264074  0.264072 -0.254204   
66  4.074287  4.077565  0.328535  0.326773  0.342691  0.340616 -0.146902   
67  2.821466  2.821061  0.587021  0.586958  0.718808  0.718827 -0.376715   
68  3.148663  3.144413  0.944565  0.945800  0.108079  0.108169 -0.400807   
69  1.053902  1.053814  0.158410  0.158405  0.170682  0.170682 -0.437272   
70  4.098818  4.100145  0.577946  0.578080  0.780843  0.780661 -0.513084   
72  4.359582  4.359630  0.381763  0.381762  0.230978  0.230978 -0.651724   
75  0.611514  0.611464  0.469695  0.469716  0.422770  0.422764 -0.270563   
76  2.849047  2.764298  0.467057  0.491245  0.280246  0.298147 -0.886181   
77  1.255411  1.255678  0.719380  0.719452  0.653040  0.653023 -0.691772   
81  4.623603  4.624223  0.819302  0.819080  0.172648  0.172608 -0.215059   
82  2.968353  2.968168  0.073380  0.073320  0.737186  0.73

In [16]:
#next 7 blocks show the average distance between initial guess and real parameter
disIk = np.abs(solved['Ik'] - solved['Rk']).mean()
disIk

1.1757920862723674

In [17]:
disIvbar = np.abs(solved['Ivbar'] - solved['Rvbar']).mean()
disIvbar

0.2684872777950839

In [18]:
disIv0 = np.abs(solved['Iv0'] - solved['Rv0']).mean()
disIv0

0.2608432022464965

In [19]:
disIsigma = np.abs(solved['Isigma'] - solved['Rsigma']).mean()
disIsigma

0.29376722885605033

In [20]:
disIrho = np.abs(solved['Irho'] - solved['Rrho']).mean()
disIrho

0.25911951876417116

In [21]:
disII1 = np.abs(solved['II1'] - solved['RI1']).mean()
disII1

0.00036305040969208377

In [22]:
disII2 = np.abs(solved['II2'] - solved['RI2']).mean()
disII2

0.00031009655043543177

In [23]:
#next 7 blocks show the average distance between optimal found and real parameter
disOk = np.abs(solved['Ok'] - solved['Rk']).mean()
disOk

0.0035757197794941058

In [24]:
disOvbar = np.abs(solved['Ovbar'] - solved['Rvbar']).mean()
disOvbar

0.0010780179481016923

In [25]:
disOsigma = np.abs(solved['Osigma'] - solved['Rsigma']).mean()
disOsigma

0.04531444425785349

In [26]:
disOrho = np.abs(solved['Orho'] - solved['Rrho']).mean()
disOrho

0.016047778906912637

In [27]:
disOv0 = np.abs(solved['Ov0'] - solved['Rv0']).mean()
disOv0

0.001289194277595836

In [28]:
disOI1 = np.abs(solved['OI1'] - solved['RI1']).mean()
disOI1

5.044731611947653e-05

In [29]:
disOI2 = np.abs(solved['OI2'] - solved['RI2']).mean()
disOI2

4.6242136822970816e-05