In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.special import erf
from scipy.stats import norm
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
#%matplotlib tk

In [2]:
result = pd.read_csv("/home/lin/git/summerProject/Heston++onSPXonly_ana_100run")

In [3]:
result[['time', 'iteration', 'pv', 'jac', 'lin_sys', 'e0', 'e*', 'Je', 'Dp', 'count','count2', 'count7']].describe()

time     iteration            pv           jac       lin_sys  \
count  100.000000    100.000000    100.000000    100.000000    100.000000   
mean     8.073009    802.540000    931.780000    802.550000    930.780000   
std     33.717237   3289.466115   3981.229856   3289.464239   3981.229856   
min      0.150323     16.000000     17.000000     16.000000     16.000000   
25%      0.379263     40.000000     41.000000     40.000000     40.000000   
50%      0.749229     74.000000     87.500000     74.000000     86.500000   
75%      1.708868    175.250000    186.250000    175.250000    185.250000   
max    293.842522  28279.000000  35644.000000  28279.000000  35643.000000   

                 e0            e*            Je          Dp       count  \
count  1.000000e+02  1.000000e+02  1.000000e+02  100.000000  100.000000   
mean   1.373096e+06  1.203211e-05  4.154602e-04    0.000181    1.340000   
std    1.143972e+07  5.780694e-05  1.183564e-03    0.000338    0.901402   
min    9.874506e-04  1.595371e-12  8.066112e-12    0.000000    1.000000   
25%    3.987190e-02  8.075369e-11  5.039480e-05    0.000024    1.000000   
50%    1.465388e-01  9.399302e-11  1.161729e-04    0.000075    1.000000   
75%    2.885694e-01  9.888672e-11  2.757990e-04    0.000185    1.000000   
max    1.138110e+08  4.667933e-04  9.551195e-03    0.002517    7.000000   

       count2      count7  
count   100.0  100.000000  
mean      0.0    0.340000  
std       0.0    0.901402  
min       0.0    0.000000  
25%       0.0    0.000000  
50%       0.0    0.000000  
75%       0.0    0.000000  
max       0.0    6.000000

In [4]:
result['stopped_by'].unique()
#This show the reasons for stopping:
#1 - stopped by small gradient J^T e
#2 - stopped by small Dp
#3 - stopped by itmax
#4 - singular matrix. Restart from current p with increased \mu
#5 - no further error reduction is possible. Restart with increased mu
#6 - stopped by small ||e||_2
#7 - stopped by invalid (i.e. NaN or Inf) "func" values; a user error

array([6, 5, 1])

In [5]:
#number of solved cases, allowing restart when stopped by 7 or 2
solved = result[result['stopped_by'] == 6]
solved.count().unique()

array([90])

In [6]:
#percentage of solved
solved.count().unique()/result.count().unique()

array([0.9])

In [7]:
#number of solved cases at the first try
solved_first_time = solved[solved['count'] == 1]
solved_first_time.count().unique()

array([76])

In [8]:
#number of cases stopped by small Dp (update of parameter)
DP = result[result['stopped_by'] == 2]
DP.count().unique()

array([0])

In [9]:
#number of cases that stopped by max iteration
itmax = result[result['stopped_by'] == 3]
itmax.count().unique()

array([0])

In [10]:
#number of cases that stopped by mall gradient J^T e
smalJac = result[result['stopped_by'] == 1]
smalJac.count().unique()

array([1])

In [11]:
#average time for all solved cases
solved['time'].describe()['mean']

3.9679969

In [12]:
#average time for cases solved without restart
solved_first_time['time'].describe()['mean']

4.293366894736842

In [13]:
#Average number of iteration for solved cases
solved_first_time['iteration'].describe()['mean']

431.3157894736842

In [14]:
#Average number of iteration for all solved cases
solved['iteration'].describe()['mean']

401.35555555555555

In [15]:
#All solved cases
solved[['Ok', 'Rk', 'Ovbar', 'Rvbar','Ov0', 'Rv0', 'Orho', 'Rrho', 'Osigma', 'Rsigma', 'OI1', 'RI1', 'OI2', 'RI2', 'stopped_by', 'e*']]

Ok        Rk     Ovbar     Rvbar       Ov0       Rv0      Orho  \
0   1.101351  1.091920  0.460541  0.462785  0.247156  0.247063 -0.642977   
2   2.250448  2.228640  0.739134  0.872436  0.391317  0.468001 -0.153419   
3   4.806764  4.508319  0.386603  0.807836  0.113186  0.241476 -0.299815   
4   2.454574  3.331711  0.401473  0.636128  0.796121  0.772766 -0.490293   
5   3.812073  4.692535 -0.019133  0.243724  1.034419  0.868030 -0.675422   
6   2.750371  4.444546  0.537085  0.706773  0.937139  0.694078 -0.789314   
7   3.788450  2.815968  0.262987  0.445753  0.282865  0.775985 -0.462269   
8   1.263685  1.460961  0.337060  0.399941  1.039946  0.902791 -0.292119   
9   0.961365  0.957368  0.618602  0.621246  0.691744  0.765293 -0.775618   
10  1.059736  1.922033  0.137950  0.525693  0.559959  0.579307 -0.465334   
12  2.625276  2.173594  0.326260  0.329152  0.143534  0.143418 -0.705174   
13  0.996065  0.507458  0.340172  0.076420  0.277199  0.490687 -1.773816   
14  3.868460  3.593365  0.579253  0.802586  0.567076  0.926012 -0.209551   
15  1.145192  1.246674  0.143243  0.193782  0.583981  0.645794 -0.985770   
16  3.388547  4.728764  0.510194  0.279462  0.313539  0.161464 -0.166293   
18  3.338106  3.207369  0.507975  0.517403  0.193263  0.195277 -0.561567   
19  3.943414  4.195298  0.195089  0.257243  0.882928  0.859569 -0.611465   
20  2.685128  3.079323  0.053964  0.232234  0.964587  0.926913 -0.484967   
21  0.674055  0.641317  0.511040  0.519993  0.299747  0.299478 -0.569070   
22  3.357339  0.830799  0.583762  0.485486  0.318577  0.499692 -1.771367   
23  1.919306  1.169543  0.618086  0.945861  0.267871  0.412466 -1.457244   
24  4.544801  4.643733  0.517529  0.514878  0.290298  0.287720 -0.762613   
25  1.304332  0.832326  0.586851  0.559564  0.400140  0.430297 -0.344569   
26  0.666439  0.585122  0.295652  0.225211  0.518676  0.520765 -0.676715   
27  4.343267  2.911804  0.733423  0.886901  0.231690  0.268906 -0.615244   
28  4.787566  3.609192  0.584014  0.562406  0.407403  0.441053 -0.267246   
29  2.949396  2.772765  0.199375  0.156558  0.648382  0.652014 -0.409504   
30  3.344690  3.521082  0.864011  0.847859  0.363394  0.357663 -0.654795   
31  4.033844  4.067511  0.241909  0.242524  0.400481  0.392565 -0.825217   
32  2.884141  2.270529  0.592064  0.798396  0.132535  0.166648 -1.161753   
..       ...       ...       ...       ...       ...       ...       ...   
64  2.175180  1.922801  0.281999  0.143688  0.824445  0.845430 -0.600458   
65  0.949112  0.823916  0.226622  0.217290  0.265633  0.264072 -0.253267   
66  3.467234  4.077565  0.285263  0.326773  0.308800  0.340616 -0.155632   
67  3.044758  2.821061  0.617750  0.586958  0.707668  0.718827 -0.378541   
68  3.403135  3.144413  0.737555  0.945800  0.085910  0.108169 -0.452475   
69  1.094782  1.053814  0.158709  0.158405  0.166138  0.170682 -0.443548   
70  3.427413  4.100145  0.471243  0.578080  0.871841  0.780661 -0.483119   
71  3.593700  1.760504  0.249563  0.250870  0.196393  0.507324 -0.655993   
72  4.333290  4.359630  0.382207  0.381762  0.231189  0.230978 -0.651556   
73  1.483748  1.232209  0.882331  0.937210  0.538942  0.629597 -1.041773   
74  1.803464  3.307682 -0.124244  0.475873  0.870886  0.742806 -0.297398   
75  0.674634  0.611464  0.447674  0.469716  0.430695  0.422764 -0.268120   
76  2.922914  2.764298  0.471686  0.491245  0.283160  0.298147 -0.828204   
77  1.133912  1.255678  0.681571  0.719452  0.660763  0.653023 -0.687134   
78  1.508792  0.817658  0.618537  0.050006  0.665792  0.925230 -0.755284   
80  1.484010  1.158994  0.652974  0.518800  0.666085  0.826693 -1.190346   
81  4.339930  4.624223  0.955137  0.819080  0.197206  0.172608 -0.202239   
82  3.204633  2.968168  0.144702  0.073320  0.726264  0.737194 -0.490417   
83  2.761932  1.418416  0.748086  0.109466  0.774025  0.933052 -0.577335   
84  4.618320  4.633710  0.081289  0.081507  0.203457  0.204986 -0.328742   
87  3.224270  2.438392  0.544812  0.465290  0.526756  0.61

In [16]:
#next 7 blocks show the average distance between initial guess and real parameter
disIk = np.abs(solved['Ik'] - solved['Rk']).mean()
disIk

1.282020543200164

In [17]:
disIvbar = np.abs(solved['Ivbar'] - solved['Rvbar']).mean()
disIvbar

0.2721187220371466

In [18]:
disIv0 = np.abs(solved['Iv0'] - solved['Rv0']).mean()
disIv0

0.2762051001145511

In [19]:
disIsigma = np.abs(solved['Isigma'] - solved['Rsigma']).mean()
disIsigma

0.3023424069704593

In [20]:
disIrho = np.abs(solved['Irho'] - solved['Rrho']).mean()
disIrho

0.2539841732051876

In [21]:
disII1 = np.abs(solved['II1'] - solved['RI1']).mean()
disII1

0.00033293649515407723

In [22]:
disII2 = np.abs(solved['II2'] - solved['RI2']).mean()
disII2

0.0003037257391168832

In [23]:
#next 7 blocks show the average distance between optimal found and real parameter
disOk = np.abs(solved['Ok'] - solved['Rk']).mean()
disOk

0.49415020186139025

In [24]:
disOvbar = np.abs(solved['Ovbar'] - solved['Rvbar']).mean()
disOvbar

0.12047166967583749

In [25]:
disOsigma = np.abs(solved['Osigma'] - solved['Rsigma']).mean()
disOsigma

0.07521887978501866

In [26]:
disOrho = np.abs(solved['Orho'] - solved['Rrho']).mean()
disOrho

0.10613231651130389

In [27]:
disOv0 = np.abs(solved['Ov0'] - solved['Rv0']).mean()
disOv0

0.0843721771722859

In [28]:
disOI1 = np.abs(solved['OI1'] - solved['RI1']).mean()
disOI1

0.003166987580934268

In [29]:
disOI2 = np.abs(solved['OI2'] - solved['RI2']).mean()
disOI2

0.002699038127278141